/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.107
 * Generated at: 2021-06-29 02:25:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.demo.chart;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import project.common.bean.*;
import project.common.util.*;
import java.util.*;

public final class fusioncharts_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/fusioncharts/include/fusioncharts.jsp", Long.valueOf(1607937221974L));
    _jspx_dependants.put("/common/include/webdek/bottom.jsp", Long.valueOf(1607937169531L));
    _jspx_dependants.put("/common/include/webdek/layout.jsp", Long.valueOf(1622679572879L));
    _jspx_dependants.put("/common/include/webdek/title.jsp", Long.valueOf(1607937169653L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Grid default</title>\r\n");
      out.write('\r');
      out.write('\n');

	DataMap paramDataMap = (DataMap)request.getAttribute(CommonConfig.PARAM_ATT_KEY);
	if(paramDataMap == null){
		paramDataMap = new DataMap(request);
	}
	String menuId = paramDataMap.getString(CommonConfig.MENU_ID_KEY);

	String userid = (String)request.getSession().getAttribute(CommonConfig.SES_USER_ID_KEY);
	String username = (String)request.getSession().getAttribute(CommonConfig.SES_USER_NAME_KEY);
	String compky = (String)request.getSession().getAttribute(CommonConfig.SES_USER_COMPANY_KEY);
	String deptid = (String)request.getSession().getAttribute(CommonConfig.SES_DEPT_ID_KEY);
	String menukey = (String)request.getSession().getAttribute(CommonConfig.SES_MENU_GROUP_KEY);
	String langky = (String)request.getSession().getAttribute(CommonConfig.SES_USER_LANGUAGE_KEY);
	
	DataMap userInfo = (DataMap)request.getSession().getAttribute(CommonConfig.SES_USER_INFO_KEY);
	
	ArrayList usrloList = (ArrayList)request.getAttribute(CommonConfig.SES_USER_LAYOUT_LIST_KEY);
	ArrayList usrphList = (ArrayList)request.getAttribute(CommonConfig.SES_USER_SEARCHPARAM_LIST_KEY);
	ArrayList usrpiList = (ArrayList)request.getAttribute(CommonConfig.SES_USER_SEARCHPARAM_DEFAULT_KEY);
	
	String theme =(String)request.getSession().getAttribute(CommonConfig.SES_USER_THEME_KEY);
	
	Map headRow;

      out.write("\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<META HTTP-EQUIV=\"Expires\" CONTENT=\"Mon, 06 Jan 1990 00:00:01 GMT\">\r\n");
      out.write("<META HTTP-EQUIV=\"Expires\" CONTENT=\"-1\">\r\n");
      out.write("<META HTTP-EQUIV=\"Pragma\" CONTENT=\"no-cache\">\r\n");
      out.write("<META HTTP-EQUIV=\"Cache-Control\" CONTENT=\"no-cache\">\r\n");

if(compky != null){
		
	if(compky.equals("GCCL")){

      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/common/theme/webdek/css/layout_GCCL.css\"/>\r\n");

	}

      out.write('\r');
      out.write('\n');

	if(compky.equals("GCLC")){

      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/common/theme/webdek/css/layout_green.css\"/>\r\n");

	}
}else{

      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/common/theme/webdek/css/layout.css\"/>\r\n");
      out.write("\r\n");
		
}

      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/common/theme/webdek/css/content_ui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/common/theme/webdek/css/multiple-select.css\">\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/jquery.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/jquery-ui.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/jquery-ui.custom.js\"></script>\r\n");

	if(langky != null && (langky.equals("CN") || langky.equals("ZH"))){

      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/datepicker/jquery.ui.datepicker-zh-CN.js\"></script>\r\n");

	}else if(langky != null && langky.equals("EN")){

      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/datepicker/jquery.ui.datepicker-en-GB.js\"></script>\r\n");

	}else{

      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/datepicker/jquery.ui.datepicker-ko.js\"></script>\r\n");

	}

      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/jquery.plugin.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/jquery.form.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/jquery.cookie.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/jquery.mousewheel.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/jquery.ui.monthpicker.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/jquery.ui.timepicker.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/multiple-select.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/json2.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/big.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/dataMap.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/configData.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/label.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/lang/label-");
      out.print(langky);
      out.write(".js?v=");
      out.print(System.currentTimeMillis());
      out.write("\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/lang/message-");
      out.print(langky);
      out.write(".js?v=");
      out.print(System.currentTimeMillis());
      out.write("\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/site.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/commonUtil.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common");
      out.print(theme);
      out.write("/js/theme.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/dataBind.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/input.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/netUtil.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/ui.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/bigdata.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/dataRequest.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/grid.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/layoutSave.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/validateUtil.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/page.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- FusionCharts -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"/fusioncharts/js/fusioncharts.js\"></script>\r\n");
      out.write("<!-- jQuery-FusionCharts -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"/fusioncharts/js/jquery-fusioncharts.min.js\"></script>\r\n");
      out.write("<!-- Fusion Theme -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"/fusioncharts/js/themes/fusioncharts.theme.fusion.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");

if(usrloList != null && usrloList.size() > 0){
	for(int i=0;i<usrloList.size();i++){
		headRow = (Map)usrloList.get(i);

      out.write("\r\n");
      out.write("gridList.gridLayOutMap.put('");
      out.print(headRow.get("COMPID"));
      out.write(' ');
      out.print(headRow.get("LYOTID"));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(headRow.get("LAYDAT"));
      out.write("');\r\n");

	}
}

      out.write("\r\n");
      out.write("\r\n");

if(usrphList != null && usrphList.size() > 0){
	for(int i=0;i<usrphList.size();i++){
		headRow = (Map)usrphList.get(i);

      out.write("\r\n");
      out.write("\r\n");
      out.write("inputList.addUserParamList('");
      out.print(headRow.get("PARMKY"));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(headRow.get("SHORTX"));
      out.write("');\r\n");

	}
}

      out.write("\r\n");
      out.write("\r\n");

if(usrpiList != null && usrpiList.size() > 0){
	for(int i=0;i<usrpiList.size();i++){
		headRow = (Map)usrpiList.get(i);

      out.write("\r\n");
      out.write("inputList.addUserParamMap('");
      out.print(headRow.get("CTRLID"));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(headRow.get("CTRVAL"));
      out.write("');\r\n");

}
}

      out.write("\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("// \tuiList.UICheck();\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tif($(\"#topFrame\",window.top.document).length >= 1){\r\n");
      out.write("\t\tvar wh = $(window.top).height();\r\n");
      out.write("\t\tvar ww = $(window.top).width();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");

			if(compky.equals("GCCL")){
		
      out.write("\r\n");
      out.write("\t\tvar bgDiv = \"<div class='bgDiv' style='height:\"+wh+\"px;width:\"+ww+\"px;position:fixed;z-index:-1;background:url(/common/theme/webdek/images/bg_full_GCCL.png) repeat center center;'></div>\";\r\n");
      out.write("\t\r\n");
      out.write("\t\t");

			}else{
		
      out.write("\r\n");
      out.write("\t\tvar bgDiv = \"<div class='bgDiv' style='height:\"+wh+\"px;width:\"+ww+\"px;position:fixed; z-index:-1;background:url(/common/theme/webdek/images/bg_full.png) repeat center center;'></div>\";\r\n");
      out.write("\t\t");

			}
		
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar ph = $(window).height();\r\n");
      out.write("\t\tvar pw = $(window).width();\r\n");
      out.write("\t\t$('body').append(bgDiv);\r\n");
      out.write("\t\t$(\".bgDiv\").css({top : -120 + \"px\", left : pw - ww + \"px\"});\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\t");

		if(compky.equals("GCCL")){
		
      out.write("\r\n");
      out.write("\t\t$(\"body\").css({backgroundColor:\"#d5ecec\"});\r\n");
      out.write("\t\t");

			}else{
		
      out.write("\r\n");
      out.write("\t\t$(\"body\").css({backgroundColor:\"#f7f4be\"});\r\n");
      out.write("\t\t");

			}
		
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$(window).resize(function(){\r\n");
      out.write("\tif($(\".bgDiv\").length >= 1){\r\n");
      out.write("\t\tvar wh = $(window.top).height();\r\n");
      out.write("\t\tvar ww = $(window.top).width();\r\n");
      out.write("\t\tvar ph = $(window).height();\r\n");
      out.write("\t\tvar pw = $(window).width();\r\n");
      out.write("\t\t$(\".bgDiv\").css({top : -120 + \"px\", left : pw - ww + \"px\", width: ww+\"px\", height:wh+\"px\"});\r\n");
      out.write("\t}\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write(" \r\n");
      out.write("<script type=\"text/javascript\" src=\"/common");
      out.print(theme);
      out.write("/js/head.js\"></script>");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("const chartData = [{\r\n");
      out.write("    label: \"Venezuela\",\r\n");
      out.write("    value: \"290\"\r\n");
      out.write("}, {\r\n");
      out.write("    label: \"Saudi\",\r\n");
      out.write("    value: \"260\"\r\n");
      out.write("}, {\r\n");
      out.write("    label: \"Canada\",\r\n");
      out.write("    value: \"180\"\r\n");
      out.write("}, {\r\n");
      out.write("    label: \"Iran\",\r\n");
      out.write("    value: \"140\"\r\n");
      out.write("}, {\r\n");
      out.write("    label: \"Russia\",\r\n");
      out.write("    value: \"115\"\r\n");
      out.write("}, {\r\n");
      out.write("    label: \"UAE\",\r\n");
      out.write("    value: \"100\"\r\n");
      out.write("}, {\r\n");
      out.write("    label: \"US\",\r\n");
      out.write("    value: \"30\"\r\n");
      out.write("}, {\r\n");
      out.write("    label: \"China\",\r\n");
      out.write("    value: \"30\"\r\n");
      out.write("}];\r\n");
      out.write("\r\n");
      out.write("const chartConfigs = {\r\n");
      out.write("        type: \"column2d\",\r\n");
      out.write("        width: \"100%\",\r\n");
      out.write("        height: \"100%\",\r\n");
      out.write("        dataFormat: \"json\",\r\n");
      out.write("        dataSource: {\r\n");
      out.write("            // Chart Configuration\r\n");
      out.write("            \"chart\": {\r\n");
      out.write("                \"caption\": \"Countries With Most Oil Reserves [2017-18]\",\r\n");
      out.write("                \"subCaption\": \"In MMbbl = One Million barrels\",\r\n");
      out.write("                \"xAxisName\": \"Country\",\r\n");
      out.write("                \"yAxisName\": \"Reserves (MMbbl)\",\r\n");
      out.write("                \"numberSuffix\": \"K\",\r\n");
      out.write("                \"theme\": \"fusion\",\r\n");
      out.write("            },\r\n");
      out.write("            // Chart Data\r\n");
      out.write("            \"data\": chartData\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\t$(\"#chart-container\").insertFusionCharts(chartConfigs);\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\tfunction searchList(){\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction commonBtnClick(btnName){\r\n");
      out.write("\t\t//commonUtil.debugMsg(\"commonBtnClick : \", arguments);\r\n");
      out.write("\t\tif(btnName == \"Search\"){\r\n");
      out.write("\t\t\tsearchList();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"deemLayer none\" id=\"contentLoading\">\r\n");
      out.write("\t<img src=\"/common/theme/webdek/images/Loading_icon.gif\" />\r\n");
      out.write("</div>\r\n");
      out.write("<!-- column edit popup -->\r\n");
      out.write("<div id=\"columnSaveLayer\" class=\"layer_popup\" style=\"left:50%;top:50%;width:584px;margin:-250px 0 0 -350px;display:none;\"><!-- 팝업 위치는 알아서 변경해주세요 -->\r\n");
      out.write("\t<div class=\"layer_search\">\r\n");
      out.write("\t\t<div class=\"layer_left section\" style=\"width:252px;margin-right:54px\"><!-- width 맞게 변경, margin-right는 가운데 width 값(layer_leftmargin:10px 포함)  -->\r\n");
      out.write("\t\t\t<strong class=\"layer_stit\">Show</strong>\r\n");
      out.write("\t\t\t<div class=\"input_list\" style=\"height:280px\"><!-- height 맞게 변경 -->\r\n");
      out.write("\t\t\t\t<div class=\"scroll tableBody\" style=\"height:252px\"><!-- height 맞게 변경  -->\r\n");
      out.write("\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<col style=\"width:250px\"/><col style=\"width:70px\"/>\r\n");
      out.write("\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t<tbody id=\"visibleList\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr CGRow=\"true\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td GCol=\"text,COLTEXT\" layoutColName=\"GRID_COL_COLNAME_*\" layoutColWidth=\"GRID_COL_COLWIDTH_*\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td GCol=\"input,COLWIDTH\" GF=\"N 4,0\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"drag_btn_box_s\">\r\n");
      out.write("\t\t\t\t<button class=\"btn btn_drag_up_all\" onclick=\"layoutSave.moveTop()\"><span></span></button>\r\n");
      out.write("\t\t\t\t<button class=\"btn btn_drag_up\" onclick=\"layoutSave.moveUp()\"><span></span></button>\r\n");
      out.write("\t\t\t\t<button class=\"btn btn_drag_down\" onclick=\"layoutSave.moveDown()\"><span></span></button>\r\n");
      out.write("\t\t\t\t<button class=\"btn btn_drag_down_all\" onclick=\"layoutSave.moveBottom()\"><span></span></button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"drag_btn_box\">\r\n");
      out.write("\t\t\t<button class=\"btn btn_drag_right_all\" onClick=\"layoutSave.moveLeft()\"><span></span></button>\r\n");
      out.write("\t\t\t<button class=\"btn btn_drag_right\" onClick=\"layoutSave.moveLeftAll()\" ><span></span></button>\r\n");
      out.write("\t\t\t<button class=\"btn btn_drag_left\" onClick=\"layoutSave.moveRight()\"><span></span></button>\r\n");
      out.write("\t\t\t<button class=\"btn btn_drag_left_all\" onClick=\"layoutSave.moveRightAll()\"><span></span></button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"layer_right section\" style=\"width:216px\"><!-- width 맞게 변경 -->\r\n");
      out.write("\t\t\t<strong class=\"layer_stit\">Hidden</strong>\r\n");
      out.write("\t\t\t<div class=\"input_list scroll tableBody\" style=\"height:280px\"><!-- height 맞게 변경 -->\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t<col style=\"width:220px\"/>\r\n");
      out.write("\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t<tbody id=\"invisibleList\">\r\n");
      out.write("\t\t\t\t\t\t<tr CGRow=\"true\">\r\n");
      out.write("\t\t\t\t\t\t\t<td GCol=\"text,COLTEXT\" layoutColName=\"GRID_COL_COLNAME_*\" layoutColWidth=\"GRID_COL_COLWIDTH_*\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"btn_wrap\" style=\"width:540px;margin-left: 20px\">\r\n");
      out.write("\t\t<div class=\"fl_l\" style=\"width:65%\">\r\n");
      out.write("\t\t\t<input type=\"button\" class=\"btn_gray\" value=\"clear\" onClick=\"layoutSave.resetLayout()\"/>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"fl_r\" style=\"width:35%\">\r\n");
      out.write("\t\t\t<input type=\"button\" class=\"btn_basic\" value=\"confirm\" onClick=\"layoutSave.saveLayout()\"/>\r\n");
      out.write("\t\t\t<input type=\"button\" class=\"btn_gray\" value=\"close\" onClick=\"hideLayoutSave()\"/>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- column edit popup -->\r\n");
      out.write("<div id=\"layerBack\" class=\"deemLayer2\" style=\"display:none;\">\r\n");
      out.write("</div>\r\n");
      out.write("<!-- grid body menu popup -->\r\n");
      out.write("<div class=\"layer_popup\" id=\"gridBodyMenuLayer\" style=\"left:100px;top:100px;width:147px;display:none;\"><!-- 팝업 위치는 알아서 변경해주세요 -->\r\n");
      out.write("\t<div class=\"right_click_box\">\r\n");
      out.write("\t\t<ul class=\"right_click_list\">\r\n");
      out.write("\t\t\t<!-- li><input type=\"button\" class=\"btn_l btn_cut off\" value=\"Cut\" onClick=\"gridList.contextMenuExec('Cut')\"/></li--><!-- 회색아이콘은 off 추가 -->\r\n");
      out.write("\t\t\t<!-- li><input type=\"button\" class=\"btn_l btn_copy\" value=\"Copy\" onClick=\"gridList.contextMenuExec('Copy')\"/></li--><!-- 회색아이콘은 off 추가 -->\r\n");
      out.write("\t\t\t<li><input type=\"button\" class=\"btn_l btn_paste\" value=\"Paste\" onClick=\"gridList.contextMenuExec('Paste')\"/></li>\r\n");
      out.write("\t\t\t<!-- li><input type=\"button\" value=\"Remove\" /></li-->\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<ul class=\"right_click_list\">\r\n");
      out.write("\t\t\t<li class=\"addMenu\"><input type=\"button\" class=\"btn_l btn_add_r\" value=\"Add\" onClick=\"gridList.contextMenuExec('Add')\"/></li>\r\n");
      out.write("\t\t\t<li class=\"addMenu\"><input type=\"button\" class=\"btn_l btn_insertion\" value=\"Insert\" onClick=\"gridList.contextMenuExec('Insert')\"/></li>\r\n");
      out.write("\t\t\t<li class=\"addMenu\"><input type=\"button\" class=\"btn_l btn_cloning\" value=\"Clone\" onClick=\"gridList.contextMenuExec('Clone')\" /></li>\r\n");
      out.write("\t\t\t<li class=\"delMenu\"><input type=\"button\" value=\"Delete\" onClick=\"gridList.contextMenuExec('Delete')\"/></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<!-- ul class=\"right_click_list\">\r\n");
      out.write("\t\t\t<li><input type=\"button\" class=\"btn_l btn_filter\" value=\"Filter\" /></li>\r\n");
      out.write("\t\t\t<li><input type=\"button\" class=\"btn_l btn_fixed_frame\" value=\"Freeze panes\" /></li>\r\n");
      out.write("\t\t</ul-->\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- grid body menu popup -->\r\n");
      out.write("<!-- grid head menu popup -->\r\n");
      out.write("<div class=\"layer_popup\" id=\"gridHeadMenuLayer\" style=\"left:200px;top:200px;width:147px;display:none;\"><!-- 팝업 위치는 알아서 변경해주세요 -->\r\n");
      out.write("\t<div class=\"right_click_box\">\r\n");
      out.write("\t\t<ul class=\"right_click_list\">\r\n");
      out.write("\t\t\t<li class=\"sortMenu\"><input type=\"button\" class=\"btn_l btn_ascending\" value=\"Sort(asc)\" onClick=\"gridList.contextMenuExec('SortAsc')\"/></li>\r\n");
      out.write("\t\t\t<li class=\"sortMenu\"><input type=\"button\" class=\"btn_l btn_descending\" value=\"Sort(desc)\" onClick=\"gridList.contextMenuExec('SortDesc')\" /></li>\r\n");
      out.write("\t\t\t<li class=\"sortMenu\"><input type=\"button\" class=\"btn_l btn_sort_del\" value=\"Sort reset\" onClick=\"gridList.contextMenuExec('SortReset')\" /></li>\r\n");
      out.write("\t\t\t<!-- li><input type=\"button\" class=\"btn_l btn_sort_edit\" value=\"Sort edit\" /></li>\r\n");
      out.write("\t\t\t<li><input type=\"button\" class=\"btn_l btn_hide\" value=\"Hidden\" /></li>\r\n");
      out.write("\t\t\t<li><input type=\"button\" class=\"btn_l btn_column_w\" value=\"Column width\" /></li-->\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<ul class=\"right_click_list\">\r\n");
      out.write("\t\t\t<li class=\"columnEdit\"><input type=\"button\" class=\"btn_l btn_column_edit\" value=\"Column edit\" onClick=\"gridList.contextMenuExec('ColumnEdit')\" /></li>\r\n");
      out.write("\t\t\t<!-- li><input type=\"button\" class=\"btn_l btn_filter\" value=\"Filter\" /></li-->\r\n");
      out.write("\t\t\t<li class=\"totalMenu\"><input type=\"button\" class=\"btn_l btn_sum_r\" value=\"Total\" onClick=\"gridList.contextMenuExec('Total')\" /></li>\r\n");
      out.write("\t\t\t<li class=\"totalMenu\"><input type=\"button\" value=\"Sub total\" onClick=\"gridList.contextMenuExec('SubTotal')\"/></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<!-- ul class=\"right_click_list\">\r\n");
      out.write("\t\t\t<li><input type=\"button\" class=\"btn_l btn_filter\" value=\"Filter\" /></li>\r\n");
      out.write("\t\t\t<li><input type=\"button\" class=\"btn_l btn_fixed_frame\" value=\"Freeze panes\" /></li>\r\n");
      out.write("\t\t</ul-->\r\n");
      out.write("\t\t<!-- >ul class=\"right_click_list\">\r\n");
      out.write("\t\t\t<li><input type=\"button\" class=\"btn_l btn_cut\" value=\"Cut\" /></li>\r\n");
      out.write("\t\t\t<li><input type=\"button\" class=\"btn_l btn_copy\" value=\"Copy\" /></li>\r\n");
      out.write("\t\t\t<li><input type=\"button\" class=\"btn_l btn_paste\" value=\"Paste\" /></li>\r\n");
      out.write("\t\t\t<li><input type=\"button\" value=\"Clear\" /></li>\r\n");
      out.write("\t\t</ul-->\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- grid head menu popup -->\r\n");
      out.write("<!-- multiinput popup -->\r\n");
      out.write("<div class=\"layer_popup\" id=\"multiInputLayer\" style=\"left:50%;top:50%;width:485px;margin:-250px 0 0 -350px;display:none;\"><!-- 팝업 위치는 알아서 변경해주세요 -->\r\n");
      out.write("\t<div class=\"layer_search\">\r\n");
      out.write("\t\t<div class=\"grid_list\" style=\"display:none;\">\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t<col style=\"width:64px\"/><col style=\"width:235px\"/><col style=\"width:71px\"/><col style=\"width:50px\"/>\r\n");
      out.write("\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"or_and\"></td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"input_box_bg\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" id=\"input01\" class=\"input_bg ta_c\" value=\"조건1 +(5 item)\" />\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"input_box_bg btn1\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" id=\"input01\" class=\"input_bg\" value=\"IN\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn_select\"><span>select</span></button>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"btn_area\"><button type=\"button\" class=\"btn btn_del2\"><span>추가</span></button></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"or_and\"><span class=\"btn_basic\">AND</span></td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"input_box_bg\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" id=\"input01\" class=\"input_bg ta_c\" value=\"조건1 +(5 item)\" />\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"input_box_bg btn1\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" id=\"input01\" class=\"input_bg\" value=\"IN\"/><button type=\"button\" class=\"btn btn_select\"><span>select</span></button>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"btn_area\"><button type=\"button\" class=\"btn btn_del2\"><span>추가</span></button></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"or_and\"><span class=\"btn_basic\">OR</span></td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"input_box_bg\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" id=\"input01\" class=\"input_bg ta_c\" value=\"조건1 +(5 item)\" />\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"input_box_bg btn1\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" id=\"input01\" class=\"input_bg\" value=\"IN\"/><button type=\"button\" class=\"btn btn_select\"><span>select</span></button>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"btn_area\"><button type=\"button\" class=\"btn btn_del2\"><span>추가</span></button></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"table_list01 scroll section\" style=\"height:200px\"><!-- 높이값 맞게 변경 -->\r\n");
      out.write("\t\t\t<table class=\"table_c tableBody\" id=\"multiInputList\">\r\n");
      out.write("\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t<col width=\"400px\"/>\r\n");
      out.write("\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t<tr CGRow=\"true\" class=\"search_area\">\r\n");
      out.write("\t\t\t\t\t<td GCol=\"input,DATA\">DATA</td>\r\n");
      out.write("\t\t\t\t</tr>\t\t\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"table_list01 scroll section\" style=\"height:200px;display:none;\"><!-- 높이값 맞게 변경 -->\r\n");
      out.write("\t\t\t<table class=\"table_c tableBody\" id=\"multiInputRangeList\">\r\n");
      out.write("\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t<col width=\"50%\"/>\r\n");
      out.write("\t\t\t\t\t<col width=\"50%\"/>\r\n");
      out.write("\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t<tr CGRow=\"true\" class=\"search_area\">\r\n");
      out.write("\t\t\t\t\t<td GCol=\"input,FROM\">FROM</td>\r\n");
      out.write("\t\t\t\t\t<td GCol=\"input,TO\">TO</td>\r\n");
      out.write("\t\t\t\t</tr>\t\t\t\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"btn_wrap\">\r\n");
      out.write("\t\t<div class=\"fl_l\">\r\n");
      out.write("\t\t\t<!-- input type=\"button\" class=\"btn_basic\" value=\"add\" /-->\r\n");
      out.write("\t\t\t<input type=\"button\" class=\"btn_gray\" value=\"reset\" onClick=\"rangeObj.clearRange('rangeSingleList')\"/>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"fl_r\">\r\n");
      out.write("\t\t\t<input type=\"button\" class=\"btn_basic\" value=\"confirm\" onClick=\"rangeObj.confirmRange()\"/>\r\n");
      out.write("\t\t\t<input type=\"button\" class=\"btn_gray\" value=\"close\" onclick=\"rangePopClose()\"/>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- multiinput popup -->\r\n");
      out.write("<!-- clipboard popup -->\r\n");
      out.write("<div class=\"layer_popup\" id=\"clipboardLayer\" style=\"left:50%;top:50%;width:585px;margin:-200px 0 0 -300px;display:none;z-index:201;\"><!-- 팝업 위치는 알아서 변경해주세요 -->\r\n");
      out.write("\t<div class=\"layer_search\">\r\n");
      out.write("\t\t<div class=\"table_list01 scroll\" style=\"height:200px\"><!-- 높이값 맞게 변경 -->\r\n");
      out.write("\t\t\t<textarea style=\"width:100%;height:100%\" id=\"clipboardLayerText\">\t\t\t\r\n");
      out.write("\t\t\t</textarea>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"btn_wrap\" style=\"width:545px;margin-left: 20px\">\r\n");
      out.write("\t\t<div class=\"fl_l\">\r\n");
      out.write("\t\t\t<!-- input type=\"button\" class=\"btn_basic\" value=\"add\" /-->\r\n");
      out.write("\t\t\t<input type=\"button\" class=\"btn_basic\" value=\"Paste\" onClick=\"gridList.clipDataView()\" id=\"clipboardLayerBtn\"/>\r\n");
      out.write("\t\t\t<span id=\"clipboardLayerDesc\">Ctrl+C copy clipboard</span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"fl_r\">\r\n");
      out.write("\t\t\t<input type=\"button\" class=\"btn_gray\" value=\"close\" onclick=\"hideClipSave()\"/>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- clipboard popup -->\r\n");
      out.write("<!-- excelUpload popup -->\r\n");
      out.write("<div class=\"layer_popup\" id=\"excelUploadLayer\" style=\"left:50%;top:50%;width:485px;margin:-250px 0 0 -350px;display:none;\"><!-- 팝업 위치는 알아서 변경해주세요 -->\r\n");
      out.write("\t<div class=\"layer_search\">\r\n");
      out.write("\t\t<div class=\"table_list01 scroll\" style=\"height:70px\"><!-- 높이값 맞게 변경 -->\r\n");
      out.write("\t\t\t<form action='/common/grid/excel/fileUp/excel.data' enctype='multipart/form-data' method='post' id='gridExcelUploadForm'>\r\n");
      out.write("\t\t\t\t<input type='file' name='gridExcelUp' validate='required excel'/>\r\n");
      out.write("\t\t\t\t<input type='submit' value='upload'/>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"btn_wrap\" style=\"width:455px;margin-left: 15px\">\r\n");
      out.write("\t\t<div class=\"fl_l\">\r\n");
      out.write("\t\t\t<input type=\"button\" class=\"btn_basic\" value=\"Template\" onClick=\"gridList.excelUploadTemplateDown()\"/>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"fl_r\">\r\n");
      out.write("\t\t\t<input type=\"button\" class=\"btn_gray\" value=\"close\" onclick=\"hideExcelUpload()\"/>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- excelUpload popup -->\r\n");
      out.write("<!-- fileUpload popup -->\r\n");
      out.write("<div class=\"layer_popup\" id=\"fileUploadLayer\" style=\"left:50%;top:50%;width:485px;margin:-250px 0 0 -350px;display:none;\"><!-- 팝업 위치는 알아서 변경해주세요 -->\r\n");
      out.write("\t<div class=\"layer_search\">\r\n");
      out.write("\t\t<div class=\"table_list01 scroll\" style=\"height:30px\"><!-- 높이값 맞게 변경 -->\r\n");
      out.write("\t\t\t<form action='/common/fileUp/file.data' enctype='multipart/form-data' method='post' id='fileUploadForm'>\r\n");
      out.write("\t\t\t\t<input type='hidden' name='FILE_TYPE'/>\r\n");
      out.write("\t\t\t\t<input type='file' name='fileUp' validate='required'/>\t\t\t\t\r\n");
      out.write("\t\t\t\t<input type='submit' value='upload'/>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"table_list01 scroll\" style=\"height:200px;\"><!-- 높이값 맞게 변경 -->\r\n");
      out.write("\t\t\t<span id=\"fileNameView\"></span><br/>\r\n");
      out.write("\t\t\t<img id=\"fileImageView\" src=\"\" height=\"180px\" onClick=\"gridList.fileDownload()\"/>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"btn_wrap\" style=\"width:455px;margin-left: 15px\">\r\n");
      out.write("\t\t<div class=\"fl_l\">\r\n");
      out.write("\t\t\t<input type=\"button\" class=\"btn_basic\" value=\"Download\" onClick=\"gridList.fileDownload()\"/>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"fl_r\">\r\n");
      out.write("\t\t\t<input type=\"button\" class=\"btn_basic\" value=\"delete\" onclick=\"gridList.fileDelete()\"/>\r\n");
      out.write("\t\t\t<input type=\"button\" class=\"btn_gray\" value=\"close\" onclick=\"hideFileUpload()\"/>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- fileUpload popup -->\r\n");
      out.write("<!-- MFileUpload popup -->\r\n");
      out.write("<div class=\"layer_popup\" id=\"mFileUploadLayer\" style=\"left:50%;top:50%;width:355px;margin:-250px 0 0 -350px;display:none;\"><!-- 팝업 위치는 알아서 변경해주세요 -->\r\n");
      out.write("\t<div class=\"layer_search scroll\" style=\"width:340px\">\r\n");
      out.write("\t\t<div class=\"table_list01\"><!-- 높이값 맞게 변경 -->\r\n");
      out.write("\t\t\t<form action='/common/fileUp/mfile.data' enctype='multipart/form-data' method='post' id='mFileUploadForm'>\r\n");
      out.write("\t\t\t\t<input type='hidden' name='FILE_TYPE'/>\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"GUUID\" />\t\t\t\t\r\n");
      out.write("\t\t\t\t<input type='file' name='fileUp0' validate='required'/><br/>\t\t\t\t\r\n");
      out.write("\t\t\t\t<input type=\"button\" class=\"btn_basic\" value=\"Add\" onClick=\"mFileAdd()\" style=\"margin-bottom: 20px\"/><br/>\r\n");
      out.write("\t\t\t\t<input type='submit' value='upload' style=\"margin-top: 20px\"/>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"table_list01\">\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"btn_wrap\" style=\"width:340px\">\r\n");
      out.write("\t\t<div class=\"fl_r\">\r\n");
      out.write("\t\t\t<input type=\"button\" class=\"btn_gray\" value=\"close\" onclick=\"hideMFileUpload()\"/>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- MFileUpload popup -->\r\n");
      out.write("<!-- Filter popup -->\r\n");
      out.write("<div class=\"layer_popup\" id=\"filterLayer\" style=\"left:50%;top:50%;width:484px;margin:-250px 0 0 -350px;display:none;\"><!-- 팝업 위치는 알아서 변경해주세요 -->\r\n");
      out.write("\t<div class=\"layer_search\">\r\n");
      out.write("\t\t<div class=\"layer_left section\" style=\"width:213px;\"><!-- width 맞게 변경 -->\r\n");
      out.write("\t\t\t<strong class=\"layer_stit\" CL=\"STD_COLUMN\">열</strong>\r\n");
      out.write("\t\t\t<div class=\"input_list scroll tableBody\" style=\"height:300px\"><!-- height 맞게 변경 -->\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t<col width=\"50\" />\r\n");
      out.write("\t\t\t\t\t\t<col width=\"200\" />\r\n");
      out.write("\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t<tbody id=\"filterColList\">\r\n");
      out.write("\t\t\t\t\t\t<tr CGRow=\"true\">\r\n");
      out.write("\t\t\t\t\t\t\t<td GCol=\"rowCheck\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td GCol=\"text,COLTEXT\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"layer_right section\" style=\"width:200px\"><!-- width 맞게 변경 -->\r\n");
      out.write("\t\t\t<input type=\"checkbox\" onClick=\"gridList.checkAll('filterDataList')\" />\r\n");
      out.write("\t\t\t<span class=\"layer_stit\" CL=\"STD_COLDATA\">합계항목</span>\r\n");
      out.write("\t\t\t<div class=\"input_list scroll tableBody\" style=\"height:300px\"><!-- height 맞게 변경 -->\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t<col width=\"50\" />\r\n");
      out.write("\t\t\t\t\t\t<col width=\"40\" />\r\n");
      out.write("\t\t\t\t\t\t<col width=\"200\" />\r\n");
      out.write("\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t<tbody id=\"filterDataList\">\r\n");
      out.write("\t\t\t\t\t\t<tr CGRow=\"true\">\r\n");
      out.write("\t\t\t\t\t\t\t<td GCol=\"rownum\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td GCol=\"rowCheck\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td GCol=\"text,COLTEXT\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"btn_wrap\" style=\"width:440px;margin-left: 20px\">\r\n");
      out.write("\t\t<div class=\"fl_l\" style=\"width:65%\">\r\n");
      out.write("\t\t\t<input type=\"button\" class=\"btn_gray\" value=\"clear\" onClick=\"gridList.filterDataClear()\" />\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"fl_r\" style=\"width:35%\">\r\n");
      out.write("\t\t\t<input type=\"button\" class=\"btn_basic\" value=\"confirm\" onClick=\"gridList.filterDataConfirm()\" />\r\n");
      out.write("\t\t\t<input type=\"button\" class=\"btn_gray\" value=\"close\" onClick=\"hideGridFilter()\" />\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- Filter popup -->\r\n");
      out.write("<!-- Sub total popup -->\r\n");
      out.write("<div class=\"layer_popup\" id=\"subTotalLayer\" style=\"left:50%;top:50%;width:484px;margin:-250px 0 0 -350px;display:none;\"><!-- 팝업 위치는 알아서 변경해주세요 -->\r\n");
      out.write("\t<div class=\"layer_search\">\r\n");
      out.write("\t\t<div class=\"layer_left section\" style=\"width:213px;\"><!-- width 맞게 변경 -->\r\n");
      out.write("\t\t\t<strong class=\"layer_stit\" CL=\"STD_COLUMN\">열</strong>\r\n");
      out.write("\t\t\t<div class=\"input_list scroll tableBody\" style=\"height:300px\"><!-- height 맞게 변경 -->\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t<col style=\"width:30px\"/><col style=\"width:170px\"/>\r\n");
      out.write("\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t<tbody id=\"subTotalColList\">\r\n");
      out.write("\t\t\t\t\t\t<tr CGRow=\"true\">\r\n");
      out.write("\t\t\t\t\t\t\t<td GCol=\"rowCheck\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td GCol=\"text,COLTEXT\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"layer_right section\" style=\"width:200px\"><!-- width 맞게 변경 -->\r\n");
      out.write("\t\t\t<strong class=\"layer_stit\" CL=\"STD_TOTCOL\">합계항목</strong>\r\n");
      out.write("\t\t\t<div class=\"input_list scroll tableBody\" style=\"height:300px\"><!-- height 맞게 변경 -->\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t<col style=\"width:30px\"/><col style=\"width:170px\"/>\r\n");
      out.write("\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t<tbody id=\"subTotalDataList\">\r\n");
      out.write("\t\t\t\t\t\t<tr CGRow=\"true\">\r\n");
      out.write("\t\t\t\t\t\t\t<td GCol=\"rowCheck\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td GCol=\"text,COLTEXT\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"btn_wrap\">\r\n");
      out.write("\t\t<div class=\"fl_l\" style=\"width:65%\">\r\n");
      out.write("\t\t\t<input type=\"button\" class=\"btn_gray\" value=\"clear\" onClick=\"gridList.subTotalClear()\" />\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"fl_r\" style=\"width:35%\">\r\n");
      out.write("\t\t\t<input type=\"button\" class=\"btn_basic\" value=\"confirm\" onClick=\"gridList.subTotalConfirm()\" />\r\n");
      out.write("\t\t\t<input type=\"button\" class=\"btn_gray\" value=\"close\" onClick=\"hideGridSubTotal()\" />\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- Sub total popup -->\r\n");
      out.write("<!-- multiinput popup -->\r\n");
      out.write("<div class=\"layer_popup\" id=\"rangeLayer\" style=\"left:50%;top:50%;width:400px; transform: translate(-50%, -50%);display:none;\"><!-- 팝업 위치는 알아서 변경해주세요 -->\r\n");
      out.write("\t<div class=\"tabs content_layout\">\r\n");
      out.write("\t\t<ul class=\"tab tab_style02\">\r\n");
      out.write("\t\t\t<li><a href=\"#rangeLayer-tab1\"><span>단일값</span></a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#rangeLayer-tab2\"><span>범위값</span></a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<div id=\"rangeLayer-tab1\">\r\n");
      out.write("\t\t\t<div class=\"table_box section\">\r\n");
      out.write("\t\t\t\t<div class=\"table_list01\" style=\"height:550px;\">\r\n");
      out.write("\t\t\t\t\t<!-- thead tbody width값 맞춤-->\r\n");
      out.write("\t\t\t\t\t<div class=\"table_thead\">\r\n");
      out.write("\t\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width=\"50px\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width=\"100px\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width=\"50px\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width=\"160px\" />\r\n");
      out.write("\t\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th CL='BOTTOM_NUM'></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th CL='BOTTOM_LOGICAL'></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th CL='BOTTOM_OPER'></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th CL='BOTTOM_SINGLE'></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"scroll\">\r\n");
      out.write("\t\t\t\t\t\t<table class=\"table_c\">\r\n");
      out.write("\t\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width=\"50px\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width=\"100px\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width=\"50px\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width=\"160px\" />\r\n");
      out.write("\t\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<tbody id=\"rangeSingleList\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr CGRow=\"true\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td GCol=\"rownum\">1</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td GCol=\"select,LOGICAL\" class=\"ico\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"OR\">OR</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"AND\">AND</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td GCol=\"select,OPER\" class=\"ico\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"E\">=</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"N\">≠</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"LT\">＜</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"GT\">＞</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"LE\">≤</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"GE\">≥</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td GCol=\"input,DATA\">DATA</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"btn_wrap\">\r\n");
      out.write("\t\t\t\t\t<div class=\"fl_l\">\r\n");
      out.write("\t\t\t\t\t\t<!-- input type=\"button\" class=\"btn_basic\" value=\"add\" /-->\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" class=\"btn_gray\" value=\"reset\" onClick=\"rangeObj.clearRange('rangeSingleList')\"/>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"fl_r\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" class=\"btn_basic\" value=\"confirm\" onClick=\"rangeObj.confirmRange()\"/>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" class=\"btn_gray\" value=\"close\" onclick=\"rangePopClose()\"/>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"rangeLayer-tab2\">\r\n");
      out.write("\t\t\t<div class=\"table_box section\">\r\n");
      out.write("\t\t\t\t<div class=\"table_list01\" style=\"height:550px;\">\r\n");
      out.write("\t\t\t\t\t<!-- thead tbody width값 맞춤-->\r\n");
      out.write("\t\t\t\t\t<div class=\"table_thead\">\r\n");
      out.write("\t\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t\t<caption>table list head</caption>\r\n");
      out.write("\t\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width=\"50px\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width=\"50px\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width=\"130px\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width=\"130px\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th CL='BOTTOM_NUM'></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th CL='BOTTOM_OPER'></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th CL='BOTTOM_FROM'></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th CL='BOTTOM_TO'></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"scroll\">\r\n");
      out.write("\t\t\t\t\t\t<table class=\"table_c\">\r\n");
      out.write("\t\t\t\t\t\t\t<caption>table list head</caption>\r\n");
      out.write("\t\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width=\"50px\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width=\"50px\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width=\"130px\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width=\"130px\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<tbody id=\"rangeRangeList\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr CGRow=\"true\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td GCol=\"rownum\">1</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td GCol=\"select,OPER\" class=\"ico\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"E\">=</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"N\">≠</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td GCol=\"input,FROM\">FROM</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td GCol=\"input,TO\">TO</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"btn_wrap\">\r\n");
      out.write("\t\t\t\t\t<div class=\"fl_l\">\r\n");
      out.write("\t\t\t\t\t\t<!-- input type=\"button\" class=\"btn_basic\" value=\"add\" /-->\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" class=\"btn_gray\" value=\"reset\" onClick=\"rangeObj.clearRange('rangeRangeList')\"/>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"fl_r\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" class=\"btn_basic\" value=\"confirm\" onClick=\"rangeObj.confirmRange()\"/>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" class=\"btn_gray\" value=\"close\" onclick=\"rangePopClose()\"/>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- multiinput popup -->");
      out.write("\r\n");
      out.write("<!-- content -->\r\n");
      out.write("<div class=\"content_wrap\">\r\n");
      out.write("\t<div class=\"content_inner\">\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\t\t<!-- div class=\"title-box\">\r\n");
      out.write("\t\t\t<h2 class=\"title\">기본조회</h2>\r\n");
      out.write("\t\t\t<div class=\"location\">\r\n");
      out.write("\t\t\t\t<span class=\"icon-home\">HOME</span><span class=\"icon-gt\">&gt;</span><span>기본조회</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div-->");
      out.write("\r\n");
      out.write("\t\t<div class=\"content_serch\" id=\"searchArea\">\r\n");
      out.write("\t\t\t<div class=\"btn_wrap\">\r\n");
      out.write("\t\t\t\t<div class=\"fl_l\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"fl_r\">\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" CB=\"Search SEARCH BTN_SEARCH\" />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"search_inner\">\r\n");
      out.write("\t\t\t\t<div class=\"search_wrap \">\r\n");
      out.write("\t\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t\t<dt CL=\"STD_SEARCH\"></dt>\r\n");
      out.write("\t\t\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"input\" name=\"Search\" UIInput=\"S,SHAREMA\" IAname=\"Search\" UIFormat=\"U\"/>\r\n");
      out.write("\t\t\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t\t</dl>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"btn_tab\">\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" class=\"btn_more\" value=\"more\" onclick=\"searchMore()\"/>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("        <div class=\"search_next_wrap\">\r\n");
      out.write("\t\t\t<div class=\"content_layout tabs\">\r\n");
      out.write("\t\t\t\t<ul class=\"tab tab_style02\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#tab1-1\"><span>chart</span></a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<div class=\"table_box section\" id=\"tab1-1\">\r\n");
      out.write("\t\t\t\t\t<div id=\"chart-container\">FusionCharts will render here</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- // content -->\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\textendSizeType = false;\r\n");
      out.write("\t$extenSizeBtn = jQuery(\".btn_extend\");\r\n");
      out.write("\tfor(var i=0;i<$extenSizeBtn.length;i++){\r\n");
      out.write("\t\tvar $tmpScroll = $extenSizeBtn.eq(i).parents(\".content_layout\");\r\n");
      out.write("\t\tvar tmpIndex = $contentLayout.index($tmpScroll);\r\n");
      out.write("\t\t$extenSizeBtn.eq(i).attr(\"extenSizeBtnNum\", tmpIndex);\r\n");
      out.write("\t}\r\n");
      out.write("\t$extenSizeBtn.click(function(event) {\r\n");
      out.write("\t\tvar $obj = jQuery(event.target);\r\n");
      out.write("\t\tif(!$obj.attr(\"extenSizeBtnNum\")){\r\n");
      out.write("\t\t\t$obj = $obj.parent();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(extendSizeType){\r\n");
      out.write("\t\t\textendSizeType = false;\r\n");
      out.write("\t\t\t$searchAreaLayer.show();\r\n");
      out.write("\t\t\tfor(var i=0;i<$sizeDragBtn.length;i++){\r\n");
      out.write("\t\t\t\t$sizeDragBtn.eq(i).show();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tfor(var i=0;i<$scrollBoxList.length;i++){\r\n");
      out.write("\t\t\t\t$scrollBoxList.eq(i).parents(\".content_layout\").css(\"margin-top\",\"0px\").show();\r\n");
      out.write("\t\t\t\t$scrollBoxList.eq(i).css(\"height\",scrollBoxHeightList[i]+\"px\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\textendSizeType = true;\r\n");
      out.write("\t\t\t$searchAreaLayer.hide();\r\n");
      out.write("\t\t\tsetScrollBoxHeightList();\r\n");
      out.write("\t\t\tfor(var i=0;i<$sizeDragBtn.length;i++){\r\n");
      out.write("\t\t\t\t$sizeDragBtn.eq(i).hide();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tvar extenSizeBtnNum = parseInt($obj.attr(\"extenSizeBtnNum\"));\r\n");
      out.write("\t\t\tfor(var i=0;i<$scrollBoxList.length;i++){\r\n");
      out.write("\t\t\t\tif(extenSizeBtnNum == i){\r\n");
      out.write("\t\t\t\t\tif($scrollBoxList.eq(i).parents('.content_layout').css(\"margin-top\",\"50px\").find(\".tab_style02\").length == 0){\r\n");
      out.write("\t\t\t\t\t\t$scrollBoxList.eq(i).css(\"height\",(bodyHeight-110)+\"px\");\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t$scrollBoxList.eq(i).css(\"height\",(bodyHeight-140)+\"px\");\r\n");
      out.write("\t\t\t\t\t}\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t$scrollBoxList.eq(i).parents(\".content_layout\").hide();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tjQuery(\"body\").find(\"input :first\").focus();\r\n");
      out.write("});\r\n");
      out.write("</script>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
