/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.107
 * Generated at: 2021-02-22 01:29:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class common_005fezprint_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	String fileName = (String) request.getAttribute("filename");
	String andValue = (String) request.getAttribute("andvalue");
	
	String width    = (String) request.getAttribute("width");
	String height   = (String) request.getAttribute("height") ;
	
	String url      = (String) request.getAttribute("url");

	String platformUrl = url + "/eftpmanager";
	String hnwUrl = url + fileName;

	String realFile = "gc"+System.currentTimeMillis()+".ezxml";
	
	response.addHeader("content-type", "application/download");
	response.addHeader("Content-Disposition", "inline;filename="+realFile);
	response.addHeader("Pragma", "no-cache;");

      out.write("\r\n");
      out.write("<EzApplication\r\n");
      out.write("\t noTitle=\"no\" title=\"\" fullScreen=\"no\" addressbar=\"no\" posCenter=\"yes\" width=\"");
      out.print(width );
      out.write("\" height=\"");
      out.print(height );
      out.write("\" noResize=\"no\">\r\n");
      out.write(" \t<codebase src=\"EzipFiles/EzPlatform_1_0_0_11.ezip\" url=\"");
      out.print(platformUrl);
      out.write("\" AppPath=\"EZgen/EzPlatform_1_0_0_11.exe\" version=\"1,0,0,11\"/> \r\n");
      out.write("\t<frameset rows=\"*\" border=\"4\" borderColor=\"#FFFFFF\" bgColor=\"#ffffff\">\r\n");
      out.write("\t\t<frame name=\"top\" scrolling=\"no\" noResize=\"yes\">\r\n");
      out.write("\t\t\t<codebase src=\"EzipFiles/HnwActivw_8_0_0_96.ezip\" url=\"");
      out.print(platformUrl);
      out.write("\" AppPath=\"EZgen/HnwActivw_8_0_0_96/HnwActivw.dll\" version=\"8,0,0,96\"/>\r\n");
      out.write("\t\t\t<param name=\"hnwsrc\" value=\"");
      out.print(hnwUrl);
      out.write("\"/>\r\n");
      out.write("\t\t    <param name=\"initvalue\" value=\"");
      out.print(andValue);
      out.write("\"/> \r\n");
      out.write("\t\t\t<param name=\"UrlEncoding\" value=\"Y\"/>\r\n");
      out.write("\t\t</frame>\r\n");
      out.write("\t</frameset>\r\n");
      out.write("</EzApplication>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
