/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.107
 * Generated at: 2021-06-04 05:56:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.wms;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import project.common.bean.DataMap;
import java.util.ArrayList;
import project.common.bean.CommonConfig;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	ArrayList<DataMap> list = (ArrayList)request.getAttribute("LANGKY");

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<title>Log in</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/common/theme/webdek/css/login.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/sajo/css/style.css\">\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"/common/theme/webdek/images/logo01.png\" type=\"image/x-ico\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/jquery.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/jquery-ui.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/json2.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/jquery.cookie.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/dataMap.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/configData.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/site.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/commonUtil.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/dataBind.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/input.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/netUtil.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/ui.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/worker-ajax.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/grid.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/validateUtil.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/theme/webdek/js/theme.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/page.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("//로딩 열기\r\n");
      out.write("function loadingOpen() {\r\n");
      out.write("\r\n");
      out.write("\tvar loader = $('<div class=\"contentLoading\"></div>').appendTo('body');\r\n");
      out.write("\r\n");
      out.write("\tloader.stop().animate({\r\n");
      out.write("\t\ttop : '0px'\r\n");
      out.write("\t}, 30, function() {\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// 로딩 닫기\r\n");
      out.write("function loadingClose() {\r\n");
      out.write("\r\n");
      out.write("\tvar loader = $('.contentLoading');\r\n");
      out.write("\r\n");
      out.write("\tloader.stop().animate({\r\n");
      out.write("\t\ttop : '100%'\r\n");
      out.write("\t}, 30, function() {\r\n");
      out.write("\t\tloader.remove();\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t$(\"#COMPID\").val(\"WDSCM\");\r\n");
      out.write("\t//$(\"#COMPID\").val(\"GCCL\");\r\n");
      out.write("\r\n");
      out.write("\t//inputList.setCombo();\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#USERID\").bind(\"keyup\",function(){\r\n");
      out.write("\t\t$(this).val($(this).val().toUpperCase());\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#PASSWD\").bind(\"keyup\",function(){\r\n");
      out.write("\t\t$(this).val($(this).val().toUpperCase());\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\tvar COLOR = $.cookie(\"COLOR\");\r\n");
      out.write("\tif(COLOR){\r\n");
      out.write("\t\t//jQuery(\"#LANGKY\").val(LANGKY);\r\n");
      out.write("\t\t$(\"input[value=\"+COLOR+\"]\").attr(\"checked\",\"checked\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tvar LANGKY = $.cookie(\"LANGKY\");\r\n");
      out.write("\tif(LANGKY){\r\n");
      out.write("\t\t//jQuery(\"#LANGKY\").val(LANGKY);\r\n");
      out.write("\t\t$(\"input[value=\"+LANGKY+\"]\").attr(\"checked\",\"checked\");\r\n");
      out.write("\t}\r\n");
      out.write("\tvar USERID = $.cookie(\"USERID\");\r\n");
      out.write("\tif(USERID){\r\n");
      out.write("\t\tjQuery(\"#USERID\").val(USERID);\r\n");
      out.write("\t}\r\n");
      out.write("\tvar PASSWD = $.cookie(\"PASSWD\");\r\n");
      out.write("\tif(PASSWD){\r\n");
      out.write("\t\tjQuery(\"#PASSWD\").val(PASSWD).focus();\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t//checkEZPlatformApp();\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#searchArea [name=OWNRKY]\").on(\"change\",function(){\r\n");
      out.write("\t\tsearchwareky($(this).val());\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//\r\n");
      out.write("\tserachOwnrky();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function serachOwnrky(){\r\n");
      out.write("\r\n");
      out.write("\tvar param = new DataMap();\r\n");
      out.write("\t\r\n");
      out.write("\tvar json = netUtil.sendData({\r\n");
      out.write("\t\tmodule : \"SajoCommon\",\r\n");
      out.write("\t\tcommand : \"LOGIN_OWNRKY_COMCOMBO\",\r\n");
      out.write("\t\tsendType : \"list\",\r\n");
      out.write("\t\tparam : param\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#OWNRKY\").find(\"[UIOption]\").remove();\r\n");
      out.write("\t\r\n");
      out.write("\tvar optionHtml = inputList.selectHtml(json.data, false);\r\n");
      out.write("\t$(\"#OWNRKY\").append(optionHtml);\r\n");
      out.write("\t\r\n");
      out.write("\tvar ownrky = $.cookie(\"OWNRKY\");\r\n");
      out.write("\t\r\n");
      out.write("\tif(ownrky == ' ' || ownrky == null || ownrky == undefined){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\t$('#OWNRKY').val(ownrky);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tsearchwareky($('#OWNRKY').val());\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function searchwareky(val){\r\n");
      out.write("\tvar param = new DataMap();\r\n");
      out.write("\tparam.put(\"OWNRKY\",val);\r\n");
      out.write("\t\r\n");
      out.write("\tvar json = netUtil.sendData({\r\n");
      out.write("\t\tmodule : \"SajoCommon\",\r\n");
      out.write("\t\tcommand : \"LOGIN_WAREKY_COMCOMBO\",\r\n");
      out.write("\t\tsendType : \"list\",\r\n");
      out.write("\t\tparam : param\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#WAREKY\").find(\"[UIOption]\").remove();\r\n");
      out.write("\t\r\n");
      out.write("\tvar optionHtml = inputList.selectHtml(json.data, false);\r\n");
      out.write("\t$(\"#WAREKY\").append(optionHtml);\r\n");
      out.write("\t\r\n");
      out.write("\tvar wareky = $.cookie(\"WAREKY\");\r\n");
      out.write("\t\r\n");
      out.write("\tif(wareky == ' ' || wareky == null || wareky == undefined){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\t$('#WAREKY').val(wareky);\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function login(){\r\n");
      out.write("\t//this.location.href = \"/common/main.page\";\r\n");
      out.write("\tif(validate.check(\"searchArea\")){\r\n");
      out.write("\t\tvar param = dataBind.paramData(\"searchArea\");\r\n");
      out.write("\t\t//param.put(\"LANGKY\",\"");
      out.print(list.get(0).get("VALUE_COL"));
      out.write("\");\r\n");
      out.write("\t\tparam.put(\"LANGKY\",\"KO\");\r\n");
      out.write("\t\tparam.put(\"OWNRKY\", $(\"#OWNRKY\").val());\r\n");
      out.write("\t\tparam.put(\"WAREKY\", $(\"#WAREKY\").val());\r\n");
      out.write("\t\tvar json = netUtil.sendData({\r\n");
      out.write("\t\t\turl : \"/common/json/login.data\",\r\n");
      out.write("\t\t\tparam : param\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tif(json && json.data){\r\n");
      out.write("\t\t\tif(json.data == \"N\"){\r\n");
      out.write("\t\t\t\tcommonUtil.msg(\"존재하지 않는 사용자입니다.\");\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t} else if(json.data == \"F\"){\r\n");
      out.write("\t\t\t\tif(json.cnt < 5){\r\n");
      out.write("\t                commonUtil.msg(\"로그인 접속 오류 ( \"+json.cnt+\"/5 )\");\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("                    commonUtil.msg(\"로그인이 제한됩니다.\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}else if(json.data == \"F_LOGIN_LOCK\"){\r\n");
      out.write(" \t\t\t\tcommonUtil.msg(\"비밀번호 5회 오류로 사용이 제한 되었습니다. \\n비밀번호 찾기를 통해 임시 비밀번호를 발급받아주세요.\");\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}else if(json.data == \"F_LOGIN_INIT\"){\r\n");
      out.write("\t\t\t\tcommonUtil.msg(\"비밀번호를 변경해주세요.\");\r\n");
      out.write("\t            page.linkPopOpen(\"/GCLC/CM/CM10/CM1107_POP.page\",\"\", \"height=335,width=500,resizable=yes\");\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}else if(json.data == \"F_USE_LOCK\"){\r\n");
      out.write("                commonUtil.msg(\"사용 승인되지 않은 계정입니다.\");\r\n");
      out.write("\t\t\t}else if(json.data == \"F_PASSWORD_CHANGE\"){\r\n");
      out.write("                commonUtil.msg(\"비밀번호를 변경해주세요.(180일 경과)\");\r\n");
      out.write("                page.linkPopOpen(\"/GCLC/CM/CM10/CM1107_POP.page\",\"\", \"height=335,width=500,resizable=yes\");\r\n");
      out.write("            }else if(json.data == \"NM\"){\r\n");
      out.write("                commonUtil.msg(\"메뉴 권한이 없습니다.\");\r\n");
      out.write("                return;\r\n");
      out.write("            }else if(json.data == \"NoCon\"){\r\n");
      out.write("                commonUtil.msg(\"해당 화주에 접속권한이 없습니다.\");\r\n");
      out.write("                return;\r\n");
      out.write("            }else{\r\n");
      out.write("//             \t$.cookie(\"ownrky\",$('#OWNRKY').val(),{expries:7});\r\n");
      out.write("//             \t$.cookie(\"wareky\",$('#WAREKY').val(),{expries:7});\r\n");
      out.write("            \t\r\n");
      out.write("\t\t\t\tfor(var prop in param.map){\r\n");
      out.write("\t\t\t\t\t$.cookie(prop, param.get(prop),{expires : 7});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif(json && json.data){\r\n");
      out.write("\t\t\t\t\tthis.location.href = \"/wms/main.page\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function validationEventMsg(valObjType, objIndex, objId, objName, objValue, valType){\r\n");
      out.write("\t//commonUtil.debugMsg(\"validationEventMsg : \", arguments);\r\n");
      out.write("\tif(objName == \"USERID\"){\r\n");
      out.write("\t\treturn \"ID required.\";\r\n");
      out.write("\t}else if(objName == \"PASSWD\"){\r\n");
      out.write("\t\treturn \"Password required.\";\r\n");
      out.write("\t}else if(objName == \"LANGKY\"){\r\n");
      out.write("\t\treturn \"Language required.\";\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function checkEZPlatformApp(){\r\n");
      out.write("   if(typeof window.localStorage == 'undefined') {\r\n");
      out.write("      //alert(\"로컬 스토리지를 지원하지 않습니다.\"); //LOGIN_M0006\r\n");
      out.write("      //alert(getMsg(\"SYSTEM_NOLOCALSTORAGE\"));\r\n");
      out.write("      commonUtil.msgBox(\"SYSTEM_NOLOCALSTORAGE\");\r\n");
      out.write("      return;\r\n");
      out.write("   }\r\n");
      out.write("   var version = window.localStorage.getItem('EZPlatformApp');\r\n");
      out.write("   if( version != \"1.0.0.11\" ){\r\n");
      out.write("\t   window.open('/downloadPlatformApp.html','egzen','width=500,height=300');\r\n");
      out.write("   }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function linkEZ(){\r\n");
      out.write("\tlocation.href = '/downloadPlatformApp.html';\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"weddek\">\r\n");
      out.write("\t<!-- <div class=\"bg-gradient\"></div>\r\n");
      out.write("\t<div class=\"bg-gradient\"></div> -->\r\n");
      out.write("\t<div class=\"show\">\r\n");
      out.write("\t\t<div class=\"logos logos_sago\">\r\n");
      out.write("\t\t\t<img src=\"/sajo/images/sajo_LOGO_2.png\" />\r\n");
      out.write("\t\t\t<img src=\"/sajo/images/sajo_LOGO_1.png\" />\r\n");
      out.write("\t\t\t<img src=\"/sajo/images/sajo_LOGO_3.png\" />\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"signin\" id=\"searchArea\">\r\n");
      out.write("\t\t    <div class=\"inputbox\">\r\n");
      out.write("\t\t    \t<label>User Name</label>\r\n");
      out.write("\t\t\t    <div class=\"idbox\"><input type=\"text\" id=\"USERID\" name=\"USERID\" validate=\"required\" onkeypress=\"commonUtil.enterKeyCheck(event, 'login()')\" placeholder=\"ID\"/></div>\r\n");
      out.write("\t\t\t    <label>Password</label>\r\n");
      out.write("\t\t\t    <div class=\"pwbox\"><input type=\"password\" id=\"PASSWD\" name=\"PASSWD\" validate=\"required\" onkeypress=\"commonUtil.enterKeyCheck(event, 'login()')\" placeholder=\"Password\"/></div>\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t    <select name=\"OWNRKY\" id=\"OWNRKY\"  class=\"input\" Combo=\"\" ComboCodeView=\"true\">\r\n");
      out.write("\t\t\t    </select>\r\n");
      out.write("\t\t\t    <select name=\"WAREKY\" id=\"WAREKY\" class=\"input\" >\r\n");
      out.write("\t\t\t    </select>\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t    <div class=\"radio\" style=\"display:none\">\r\n");
      out.write("\t\t        <input type=\"radio\" id=\"RED\" name=\"COLOR\" value=\"red\"  /><label for=\"RED\">Red</label>\r\n");
      out.write("\t\t        <input type=\"radio\" id=\"SKYBLUE\" name=\"COLOR\" value=\"skyblue\" /><label for=\"SKYBLUE\">Sky Blue</label>\r\n");
      out.write("\t\t        <input type=\"radio\" id=\"navy\" name=\"COLOR\" value=\"navy\" checked=\"checked\"/><label for=\"navy\">Navy</label>\r\n");
      out.write("\t\t        <input type=\"radio\" id=\"GRAY\" name=\"COLOR\" value=\"gray\" /><label for=\"GRAY\">Gray</label>\r\n");
      out.write("\t\t        <input type=\"radio\" id=\"BLACK\" name=\"COLOR\" value=\"black\" /><label for=\"BLACK\">Black</label>\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t    <div class=\"float_btn\">\r\n");
      out.write("\t\t    \t\r\n");
      out.write("<!-- \t\t\t    <button class=\"find_IDPW\" onClick=\"window.open('/FIND_IDPW_POP.jsp','idfind','width=560,height=510,location=no,status=no,scrollbars=no');\" style=\"padding-left: 15px;\">ID/비밀번호 찾기</button> -->\r\n");
      out.write("\t\t\t    <button class=\"find_IDPW\"  onclick=\"linkEZ()\">프린트 설치</button>\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t    <div class=\"login_btn\">\r\n");
      out.write("\t\t    \t\r\n");
      out.write("\t\t   \t\t<input type=\"button\" name=\"SignIn\" value=\"Login\" onclick=\"login()\">\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t<footer>\r\n");
      out.write("\t\t<p>Copyright ⓒ 2020 SCMInno. All rights reserved.</p>\r\n");
      out.write("\t\t<select onchange=\"if(this.value) location.href=(this.value);\">\r\n");
      out.write("\t\t\t<option>Family Site</option>\r\n");
      out.write("\t\t\t<option value=\"http://www.scminno.com/\">SCMInno</option>\r\n");
      out.write("\t\t\t<option value=\"http://www.redeess.com/\">Redeess</option>\r\n");
      out.write("\t\t</select>\r\n");
      out.write("        <span>v1.0.0</span>\r\n");
      out.write("\t</footer>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
