<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<link rel="stylesheet" type="text/css" href="/common/css/layoutSave.css">
<link rel="stylesheet" type="text/css" href="/common/css/reset.css">
<title>Columns</title>
</head>
<body>
	<div class="pop">
		<div class="left">
			<div class="table type2">
				<div class="tableHeader">
					<table>
						<colgroup>
							<col width="200" />
						</colgroup>
						<thead>
							<tr>
								<th>Invisible</th>
							</tr>
						</thead>
					</table>
				</div>
				<div class="tableBody">
					<table>
						<colgroup>
							<col />
						</colgroup>
						<tbody id="invisibleList">
							<tr>
								<td>1</td>
							</tr>        
							<tr>
								<td>1</td>
							</tr> 
							<tr>
								<td>1</td>
							</tr> 
							<tr>
								<td>1</td>
							</tr>     
							<tr>
								<td>1</td>
							</tr>   
							<tr>
								<td>1</td>
							</tr>   
							<tr>
								<td>1</td>
							</tr>   
							<tr>
								<td>1</td>
							</tr>   
							<tr>
								<td>1</td>
							</tr>   
							<tr>
								<td>1</td>
							</tr>   
							<tr>
								<td>1</td>
							</tr>   
							<tr>
								<td>1</td>
							</tr>   
							<tr>
								<td>1</td>
							</tr>   
							<tr>
								<td>1</td>
							</tr>   
							<tr>
								<td>1</td>
							</tr>   
							<tr>
								<td>1</td>
							</tr>   
							<tr>
								<td>1</td>
							</tr>   
							<tr>
								<td>1</td>
							</tr>   
							<tr>
								<td>1</td>
							</tr>   
							<tr>
								<td>1</td>
							</tr>   
							<tr>
								<td>1</td>
							</tr>   
							<tr>
								<td>1</td>
							</tr>   
							<tr>
								<td>1</td>
							</tr>   
							<tr>
								<td>1</td>
							</tr>   
							<tr>
								<td>1</td>
							</tr>   
							<tr>
								<td>1</td>
							</tr>   
							<tr>
								<td>1</td>
							</tr>   
							<tr>
								<td>1</td>
							</tr>   
							<tr>
								<td>1</td>
							</tr>   
							<tr>
								<td>1</td>
							</tr>   
							<tr>
								<td>1</td>
							</tr>   
							<tr>
								<td>1</td>
							</tr>   
							<tr>
								<td>1</td>
							</tr>   
							<tr>
								<td>1</td>
							</tr>   
							<tr>
								<td>1</td>
							</tr>   
							<tr>
								<td>1</td>
							</tr>   
							<tr>
								<td>1</td>
							</tr>   
							<tr>
								<td>1</td>
							</tr>   
							<tr>
								<td>1</td>
							</tr>   
							<tr>
								<td>1</td>
							</tr>   
							<tr>
								<td>1</td>
							</tr>   
							<tr>
								<td>1</td>
							</tr>   
							<tr>
								<td>1</td>
							</tr>   
							<tr>
								<td>1</td>
							</tr>   
							<tr>
								<td>1</td>
							</tr>   
							<tr>
								<td>1</td>
							</tr>   
							<tr>
								<td>1</td>
							</tr>   
							<tr>
								<td>1</td>
							</tr>   
							<tr>
								<td>1</td>
							</tr>   
							<tr>
								<td>1</td>
							</tr>               
						</tbody>                 
					</table>
				</div>
			</div>
		</div>
		<div class="btnGroup">
				<button type="button">
					<img src="/common/images/btn_first.png" alt="" />
				</button>
				</br>
				<button type="button">
					<img src="/common/images/btn_prev.png" alt="" />
				</button>
				</br>
				<button type="button">
					<img src="/common/images/btn_next.png" alt="" />
				</button>
				</br>
				<button type="button">
					<img src="/common/images/btn_last.png" alt="" />
				</button>
		</div>
		<div class="right">
			<div class="table type2">
				<div class="tableHeader">
					<table>
						<colgroup>
							<col width="200" />
						</colgroup>
						<thead>
							<tr>
								<th>Visible</th>
							</tr>
						</thead>
					</table>
				</div>
				<div class="tableBody">
					<table>
						<colgroup>
							<col width="200" />
						</colgroup>
						<tbody id="visibleList">
							<tr>
								<td>1</td>
							</tr>        
							<tr>
								<td>1</td>
							</tr> 
							<tr>
								<td>1</td>
							</tr> 
							<tr>
								<td>1</td>
							</tr>   
							<tr>
								<td>1</td>
							</tr>     
							<tr>
								<td>1</td>
							</tr>     
							<tr>
								<td>1</td>
							</tr>     
							<tr>
								<td>1</td>
							</tr>     
							<tr>
								<td>1</td>
							</tr>     
							<tr>
								<td>1</td>
							</tr>     
							<tr>
								<td>1</td>
							</tr>     
							<tr>
								<td>1</td>
							</tr>     
							<tr>
								<td>1</td>
							</tr>     
							<tr>
								<td>1</td>
							</tr>     
							<tr>
								<td>1</td>
							</tr>     
							<tr>
								<td>1</td>
							</tr>        
							<tr>
								<td>1</td>
							</tr>     
							<tr>
								<td>1</td>
							</tr>     
							<tr>
								<td>1</td>
							</tr>     
							<tr>
								<td>1</td>
							</tr>     
							<tr>
								<td>1</td>
							</tr>     
							<tr>
								<td>1</td>
							</tr>     
							<tr>
								<td>1</td>
							</tr>     
							<tr>
								<td>1</td>
							</tr>     
							<tr>
								<td>1</td>
							</tr>     
							<tr>
								<td>1</td>
							</tr>     
							<tr>
								<td>1</td>
							</tr>     
							<tr>
								<td>1</td>
							</tr>     
							<tr>
								<td>1</td>
							</tr>     
							<tr>
								<td>1</td>
							</tr>     
							<tr>
								<td>1</td>
							</tr>     
							<tr>
								<td>1</td>
							</tr>     
							<tr>
								<td>1</td>
							</tr>     
							<tr>
								<td>1</td>
							</tr>     
							<tr>
								<td>1</td>
							</tr>     
							<tr>
								<td>1</td>
							</tr>     
							<tr>
								<td>1</td>
							</tr>     
							<tr>
								<td>1</td>
							</tr>     
							<tr>
								<td>1</td>
							</tr>     
							<tr>
								<td>1</td>
							</tr>     
							<tr>
								<td>1</td>
							</tr>     
							<tr>
								<td>1</td>
							</tr>     
							<tr>
								<td>1</td>
							</tr>     
							<tr>
								<td>1</td>
							</tr>     
							<tr>
								<td>1</td>
							</tr>     
							<tr>
								<td>1</td>
							</tr>     
							<tr>
								<td>1</td>
							</tr>     
							<tr>
								<td>1</td>
							</tr>     
							<tr>
								<td>1</td>
							</tr>        
						</tbody>                 
					</table>
				</div>
			</div>
		</div>
		<div class="tableUtil">
			<div class="rightArea">
				<button class="button type2" type="button"><img src="/common/images/ico_confirm.png" alt="" /> Confirm</button>
				<button class="button type2" type="button"><img src="/common/images/ico_cancel.png" alt="" /> Cancel</button>
			</div>
		</div>
	</div>
</body>
</html>