/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.69
 * Generated at: 2019-02-13 00:52:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.wms;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.common.bean.DataMap;
import java.util.ArrayList;
import com.common.bean.CommonConfig;
import java.net.*;
import com.common.util.*;
import com.common.util.XSSRequestWrapper;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    XSSRequestWrapper sFilter = new XSSRequestWrapper(request);

	ArrayList list  = (ArrayList)request.getAttribute("WAHMACOMBO");
	ArrayList list1 = (ArrayList)request.getAttribute("LANGKY");
	ArrayList list2 = (ArrayList)request.getAttribute("MSG");
	ArrayList list3 = (ArrayList)request.getAttribute("OWNERCOMBO");
	
	DataMap row; 
	
	InetAddress Address = InetAddress.getLocalHost();
	String clientIp = Address.getHostAddress();
	
	Object SES_USER_ID = request.getSession().getAttribute(CommonConfig.SES_USER_ID_KEY);
	
    String sloId = sFilter.getXSSFilter((String)request.getAttribute("SLOID"));
    String sloPw = sFilter.getXSSFilter((String)request.getAttribute("SLOPW"));
    String sloWk = sFilter.getXSSFilter((String)request.getAttribute("SLOWK"));
    String sloLk = sFilter.getXSSFilter((String)request.getAttribute("SLOLK"));

    String theme = sFilter.getXSSFilter(CommonConfig.SYSTEM_THEME_PATH);
	
	RSA rsa = RSA.getEncKey();
	request.setAttribute("publicKeyModulus", rsa.getPublicKeyModulus());
	request.setAttribute("publicKeyExponent", rsa.getPublicKeyExponent());
	request.getSession().setAttribute("__rsaPrivateKey__", rsa.getPrivateKey());
	

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<title>air-WMS</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/common");
      out.print(theme);
      out.write("/css/login.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/common");
      out.print(theme);
      out.write("/css/theme.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/jquery.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/jquery-ui.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/json2.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/jquery.cookie.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/dataMap.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/site.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/configData.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/commonUtil.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/dataBind.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/input.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/netUtil.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/ui.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/worker-ajax.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/bigdata.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/grid.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/validateUtil.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/page.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/label.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/wms/js/wms.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/wms/js/jsbn.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/wms/js/rsa.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/wms/js/prng4.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/wms/js/rng.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");

	for(int i=0;i<list2.size();i++){
		row = (DataMap)list2.get(i);

      out.write("\r\n");
      out.write("commonMessage.message.put(\"");
      out.print(sFilter.getXSSFilter(row.getString("MESGKY")));
      out.write('"');
      out.write(',');
      out.write('"');
      out.print(sFilter.getXSSFilter(row.getString("MESGTX")));
      out.write("\");\r\n");

	}

      out.write("\r\n");
      out.write("var $langky;\r\n");
      out.write("\r\n");
      out.write("function getMsg(msgCode){\r\n");
      out.write("\tmsgCode = $langky.val()+\"_\"+msgCode;\r\n");
      out.write("\treturn commonMessage.message.get(msgCode);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function getLabel(){\r\n");
      out.write("\treturn \"\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//로딩 열기\r\n");
      out.write("function loadingOpen() {\r\n");
      out.write("\r\n");
      out.write("\tvar loader = $('<div class=\"contentLoading\"></div>').appendTo('body');\r\n");
      out.write("\r\n");
      out.write("\tloader.stop().animate({\r\n");
      out.write("\t\ttop : '0px'\r\n");
      out.write("\t}, 30, function() {\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// 로딩 닫기\r\n");
      out.write("function loadingClose() {\r\n");
      out.write("\r\n");
      out.write("\tvar loader = $('.contentLoading');\r\n");
      out.write("\r\n");
      out.write("\tloader.stop().animate({\r\n");
      out.write("\t\ttop : '100%'\r\n");
      out.write("\t}, 30, function() {\r\n");
      out.write("\t\tloader.remove();\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("var topLabelFrame;\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t$langky = jQuery(\"#LANGKY\");\r\n");
      out.write("\t\r\n");
      out.write("\ttopLabelFrame = window;\r\n");
      out.write("\t\r\n");
      out.write("\tinputList.setCombo();\r\n");

	if(sloId != null && !sloId.equals("")){
		list = new ArrayList();
		DataMap data = new DataMap();
		data.put("VALUE_COL", sloWk);
		data.put("TEXT_COL", sloWk);
		list.add(data);
		list1 = new ArrayList();
		DataMap row1 = new DataMap();
		row1.put("VALUE_COL", sloLk);
		row1.put("TEXT_COL", sloLk);
		list1.add(row1);

      out.write("\r\n");
      out.write("\tjQuery(\"#USERID\").val(\"");
      out.print(sloId);
      out.write("\");\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\tjQuery(\"#WAREKY\").val(\"");
      out.print(sloWk);
      out.write("\");\r\n");
      out.write("\tjQuery(\"#LANGKY\").val(\"");
      out.print(sloLk);
      out.write("\");\r\n");
      out.write("\tlogin();\r\n");

	}else if(SES_USER_ID != null && !SES_USER_ID.toString().equals("")){

      out.write("\r\n");
      out.write("\tthis.location.href = \"/common/main.page\";\r\n");

	}else{

      out.write("\r\n");
      out.write("\r\n");
      out.write("\tcheckEZPlatformApp();\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"select[name=WAREKY]\").val(\"SH10\");\r\n");
      out.write("\t$(\"select[name=LANGKY]\").val(\"KR\");\r\n");
      out.write("\tvar WAREKY = $.cookie(\"WAREKY\");\r\n");
      out.write("\tif(WAREKY){\r\n");
      out.write("\t\tjQuery(\"#WAREKY\").val(WAREKY);\r\n");
      out.write("\t}\r\n");
      out.write("\t//var LANGKY = $.cookie(\"LANGKY\");\r\n");
      out.write("\t//if(LANGKY){\r\n");
      out.write("\t//\tjQuery(\"#LANGKY\").val(LANGKY);\r\n");
      out.write("\t//}\r\n");
      out.write("\tvar USERID = $.cookie(\"USERID\");\r\n");
      out.write("\tif(USERID){\r\n");
      out.write("\t\tjQuery(\"#USERID\").val(USERID);\r\n");
      out.write("\t}\r\n");
      out.write("\t//var OWNRKY = $.cookie(\"OWNRKY\");\r\n");
      out.write("\t//if(OWNRKY){\r\n");
      out.write("\t//\tjQuery(\"#OWNRKY\").val(OWNRKY);\r\n");
      out.write("\t//}\r\n");
      out.write("\t/* var PASSWD = $.cookie(\"PASSWD\");\r\n");
      out.write("\tif(PASSWD){\r\n");
      out.write("\t\tjQuery(\"#PASSWD\").val(PASSWD);\r\n");
      out.write("\t} */\r\n");

	}

      out.write("\r\n");
      out.write("\t$(\"body\").show();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function login(){\r\n");
      out.write("\t//this.location.href = \"/common/main.page\";\r\n");
      out.write("\tif(validate.check(\"searchArea\")){\r\n");
      out.write("\t\tvar param = dataBind.paramData(\"searchArea\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar paramv = new DataMap();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfor(var propv in param.map){\r\n");
      out.write("\t\t\tparamv.put(propv, param.get(propv));\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar rsaPublicKeyModulus = document.getElementById(\"rsaPublicKeyModulus\").value;\r\n");
      out.write("\t\tvar rsaPublicKeyExponent = document.getElementById(\"rsaPublicKeyExponent\").value;\r\n");
      out.write("\t\tvar encPassword = fnRsaEnc($('input[name=PASSWD]').val(), rsaPublicKeyModulus, rsaPublicKeyExponent);\r\n");
      out.write("\t\tparamv.put(\"PASSWD\", encPassword);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar json = netUtil.sendData({\r\n");
      out.write("\t\t\turl : \"/wms/json/login.data\",\r\n");
      out.write("\t\t\tparam : paramv\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(json && json.data){\r\n");
      out.write("\t\t\tif(json.data == \"F\"){\r\n");
      out.write("\t\t\t\t commonUtil.msg(getMsg(\"M0001\"));\r\n");
      out.write("\t\t\t}else if(json.data == \"F_LOGIN_DEL\"){\r\n");
      out.write("\t\t\t\tcommonUtil.msg(getMsg(\"M0002\"));\r\n");
      out.write("\t\t\t}else if(json.data == \"F_LOGIN_CONF\"){\r\n");
      out.write("\t\t\t\tcommonUtil.msg(getMsg(\"M0003\"));\r\n");
      out.write("\t\t\t}else if(json.data == \"F_LOGIN_CNT_OVER\"){\r\n");
      out.write("\t\t\t\tcommonUtil.msg(getMsg(\"M0004\"));\r\n");
      out.write("\t\t\t}else if(json.data == \"F_LOGIN_DATE_OVER\"){\r\n");
      out.write("\t\t\t\tcommonUtil.msg(getMsg(\"M0005\"));\r\n");
      out.write("\t\t\t}else if(json.data == \"F_LOGIN_PW\"){\r\n");
      out.write("\t\t\t\tcommonUtil.msg(getMsg(\"M0006\"));\r\n");
      out.write("\t\t\t}else if(json.data == \"F_LOGIN_WAREKY_ALL\"){\r\n");
      out.write("\t\t\t\tcommonUtil.msg(getMsg(\"M0007\"));\r\n");
      out.write("\t\t\t}else if(json.data == \"F_LOGIN_WAREKY\"){\r\n");
      out.write("\t\t\t\tcommonUtil.msg(getMsg(\"M0008\"));\r\n");
      out.write("\t\t\t}else if(json.data == \"F_LOGIN_OWNRKY_ALL\"){\r\n");
      out.write("\t\t\t\tcommonUtil.msg(getMsg(\"M0016\"));\r\n");
      out.write("\t\t\t}else if(json.data == \"F_LOGIN_OWNRKY\"){\r\n");
      out.write("\t\t\t\tcommonUtil.msg(getMsg(\"M0017\"));\r\n");
      out.write("\t\t\t}else if(json.data == \"F_LOGIN_RSA\"){\r\n");
      out.write("                commonUtil.msg(getMsg(\"M0024\"));\r\n");
      out.write("                this.location.reload();\r\n");
      out.write("            }else{\r\n");
      out.write("\t\t\t\tfor(var prop in param.map){\r\n");
      out.write("\t\t\t\t\tif(prop != \"PASSWD\"){\r\n");
      out.write("\t\t\t\t\t\t$.cookie(prop, param.get(prop),{\r\n");
      out.write("\t\t\t\t\t\t\t \"expires\" : 7\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t} \r\n");
      out.write("\t\t\t\tthis.location.href = \"/common/main.page\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function validationEventMsg(valObjType, objIndex, objId, objName, objValue, valType){\r\n");
      out.write("\tif(objName == \"USERID\"){\r\n");
      out.write("\t\treturn getMsg(\"M0009\");\r\n");
      out.write("\t}else if(objName == \"PASSWD\"){\r\n");
      out.write("\t\treturn getMsg(\"M0010\");\r\n");
      out.write("\t}else if(objName == \"WAREKY\"){\r\n");
      out.write("\t\treturn getMsg(\"M0011\");\r\n");
      out.write("\t}else if(objName == \"LANGKY\"){\r\n");
      out.write("\t\treturn getMsg(\"M0012\");\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function checkEZPlatformApp() \r\n");
      out.write("{\r\n");
      out.write("\tif(typeof window.localStorage == 'undefined') {\r\n");
      out.write("\t\tcommonUtil.msg(getMsg(\"M0013\"));\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\tvar version = window.localStorage.getItem('EZPlatformApp');\r\n");
      out.write("\tif( version != \"1.0.0.7\" ){\r\n");
      out.write("\t\tlocation.href = '/downloadPlatformApp.html';\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function downloadPage(){\r\n");
      out.write("\tlocation.href = '/downloadPlatformApp.html';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function changePassword(){\r\n");
      out.write("\tvar param = new DataMap();\r\n");
      out.write("    var data = dataBind.paramData(\"searchArea\");\r\n");
      out.write("    param.put(\"LANGKY\",data.get(\"LANGKY\"));\r\n");
      out.write("    param.put(\"WAREKY\",data.get(\"WAREKY\"));\r\n");
      out.write("    param.put(\"USERID\",data.get(\"USERID\"));\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    page.linkPopOpen(\"/wms/index/indexPOP.page\", param);\r\n");
      out.write("    \r\n");
      out.write("    return;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//값 존재 체크\r\n");
      out.write("function isNull(sValue) {\r\n");
      out.write("\t var value = (sValue+\"\").replace(\" \", \"\");\r\n");
      out.write("\t \r\n");
      out.write("\t if( new String(value).valueOf() == \"undefined\")\r\n");
      out.write("\t     return true;\r\n");
      out.write("\t if( value == null )\r\n");
      out.write("\t     return true;\r\n");
      out.write("\t if( value.toString().length == 0 )\r\n");
      out.write("\t     return true;\r\n");
      out.write("\t \r\n");
      out.write("\t return false;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//keyPress Enter 처리 함수\r\n");
      out.write("function checkList(num){\r\n");
      out.write("\t // 필수입력값 체크 \r\n");
      out.write("\t // 모두 입력 sendData\r\n");
      out.write("\t // 미입력 빈값 포커스\r\n");
      out.write("\t \r\n");
      out.write("\t var param  = dataBind.paramData(\"searchArea\");\r\n");
      out.write("\t \r\n");
      out.write("\t var USERID = $.trim(param.get(\"USERID\"));\r\n");
      out.write("\t var PASSWD = $.trim(param.get(\"PASSWD\"));\r\n");
      out.write("\t     \r\n");
      out.write("\t if( isNull( USERID ) ||  isNull( PASSWD )){\r\n");
      out.write("\t     if(isNull( USERID )){\r\n");
      out.write("\t         $(\"[name='USERID']\").focus();\r\n");
      out.write("\t     }else if ( isNull( PASSWD ) ){\r\n");
      out.write("\t         $(\"[name='PASSWD']\").focus();\r\n");
      out.write("\t     }\r\n");
      out.write("\t }else{\r\n");
      out.write("\t     login();\r\n");
      out.write("\t }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function fnRsaEnc(value, rsaPublicKeyModulus, rsaPpublicKeyExponent) {\r\n");
      out.write("\r\n");
      out.write("\tvar rsa = new RSAKey();\r\n");
      out.write("\trsa.setPublic(rsaPublicKeyModulus, rsaPpublicKeyExponent);\r\n");
      out.write("\tvar encValue = rsa.encrypt(value); \r\n");
      out.write("\treturn encValue;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"display:none\">\r\n");
      out.write("<div class=\"bg\">\r\n");
      out.write("    <div class=\"outerwrap\">\r\n");
      out.write("        <div class=\"innerwrap\" id=\"searchArea\">\r\n");
      out.write("            <input type=\"hidden\" id=\"USERIP\" name=\"USERIP\" value=\"");
      out.print(clientIp);
      out.write("\" />\r\n");
      out.write("\t\t\t<input type=\"hidden\" id=\"rsaPublicKeyModulus\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${publicKeyModulus}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" id=\"rsaPublicKeyExponent\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${publicKeyExponent}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("            <div class=\"HB\">\r\n");
      out.write("                <h1><img src=\"/common");
      out.print(theme);
      out.write("/images/login/HB.png\"/></h1>\r\n");
      out.write("                <div class=\"brand\"><img src=\"/common");
      out.print(theme);
      out.write("/images/login/brand.png\" alt=\"\" /></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"login\">\r\n");
      out.write("            \r\n");
      out.write("                <h1><img src=\"/common");
      out.print(theme);
      out.write("/images/login/login.png\"/></h1>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"logo\"><img src=\"/common");
      out.print(theme);
      out.write("/images/login/logo.png\" alt=\"\" /></div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"id\">\r\n");
      out.write("                    <input type=\"text\"     id=\"USERID\" name=\"USERID\" validate=\"required\" maxlength=\"80\" style=\"ime-mode:inactive\" onkeypress=\"commonUtil.enterKeyCheck(event, 'checkList()')\" />\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"pw\">\r\n");
      out.write("                    <input type=\"password\" id=\"PASSWD\" name=\"PASSWD\" validate=\"required\" maxlength=\"80\"                           onkeypress=\"commonUtil.enterKeyCheck(event, 'checkList()')\" />\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"selectWrap\">\r\n");
      out.write("\t\t            <select id=\"WAREKY\" name=\"WAREKY\" validate=\"required\" >\r\n");
      out.write("\t\t            ");

		                for(int i=0;i<list.size();i++){
		                    row = (DataMap)list.get(i);
		            
      out.write("\r\n");
      out.write("\t\t                <option value='");
      out.print(sFilter.getXSSFilter(row.getString("VALUE_COL")));
      out.write('\'');
      out.write('>');
      out.write('[');
      out.print(sFilter.getXSSFilter(row.getString("VALUE_COL")));
      out.write(']');
      out.print(sFilter.getXSSFilter(row.getString("TEXT_COL")));
      out.write("</option>\r\n");
      out.write("\t\t            ");

		                }
		            
      out.write("\r\n");
      out.write("\t\t            </select>\r\n");
      out.write("                </div>\r\n");
      out.write("                <input type =\"hidden\" id=\"OWNRKY\" name=\"OWNRKY\" value=\"1000\" />\r\n");
      out.write("                <input type =\"hidden\" id=\"LANGKY\" name=\"LANGKY\" value=\"KR\" />\r\n");
      out.write("                \r\n");
      out.write("               \r\n");
      out.write("                <div class=\"btn\">\r\n");
      out.write("                    <input type=\"submit\" value=\"Sign In\" onclick=\"login()\"/>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"selectWrap2\">\r\n");
      out.write("                    <button onclick=\"downloadPage()\">Report Tool Download</button>\r\n");
      out.write("                    <button onclick=\"changePassword()\">Change Password</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>  \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
