/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.69
 * Generated at: 2019-02-13 00:53:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.wms;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.common.bean.CommonConfig;
import com.common.bean.DataMap;
import java.util.*;
import com.common.util.XSSRequestWrapper;

public final class left_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	XSSRequestWrapper sFilter = new XSSRequestWrapper(request);

	List list = (List)request.getAttribute("list");

	String theme =  sFilter.getXSSFilter((String)request.getSession().getAttribute(CommonConfig.SES_USER_THEME_KEY));
	
	String userid = sFilter.getXSSFilter(request.getSession().getAttribute(CommonConfig.SES_USER_ID_KEY).toString());
	

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>WMS Left</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=1150\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/common");
      out.print(theme);
      out.write("/css/common.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/common");
      out.print(theme);
      out.write("/css/left.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/common");
      out.print(theme);
      out.write("/css/theme.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/jquery.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/json2.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/dataMap.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/configData.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/commonUtil.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/netUtil.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar $menuSearch;\r\n");
      out.write("\tvar menuMap = new DataMap();\r\n");
      out.write("\tvar $lastActiveObj;\r\n");
      out.write("\tvar lastActiveMenuId;\r\n");
      out.write("\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\t$menuSearch = jQuery(\"#menuSearch\");\r\n");
      out.write("\t\t//menuSearch(\"SAMPLE\");\r\n");
      out.write("\t\t$(\"body\").on('mousedown', function(e) { \r\n");
      out.write("\t\t   if( e.which == 2 ) {\r\n");
      out.write("\t\t      e.preventDefault();\r\n");
      out.write("\t\t      e.stopPropagation();\r\n");
      out.write("\t\t      e.stopImmediatePropagation();\r\n");
      out.write("\t\t      alert(\"mouse wheel click is not possible!\");\r\n");
      out.write("\t\t      return false;\r\n");
      out.write("\t\t   }\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"body\").on('click', function(e) { \r\n");
      out.write("\t\t   if( e.which == 2 ) {\r\n");
      out.write("\t\t      e.preventDefault();\r\n");
      out.write("\t\t      e.stopPropagation();\r\n");
      out.write("\t\t      e.stopImmediatePropagation();\r\n");
      out.write("\t\t      //alert(\"stop\");\r\n");
      out.write("\t\t      return false;\r\n");
      out.write("\t\t   }\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tfunction goPage(obj, url){\r\n");
      out.write("\t\tvar $obj = $(obj).parent();\r\n");
      out.write("\t\tvar menuId = $obj.attr(configData.COMMON_MENU_ID_KEY);\r\n");
      out.write("\t\tvar title = $obj.find(\"span\").text();\r\n");
      out.write("\t\tchangePage(obj, title, url, menuId);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction changePage(obj, title, url, menuId){\t\r\n");
      out.write("\t\tvar $obj = $(obj).parent();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\ttitleTxt = \"\";\r\n");
      out.write("\t\tgetTitle($obj);\r\n");
      out.write("\t\t//alert(titleTxt);\r\n");
      out.write("\t\tif(url.indexOf(\"?\") == -1){\r\n");
      out.write("\t\t\turl += \"?\"+configData.COMMON_MENU_ID_KEY+\"=\"+menuId;\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\turl += \"&\"+configData.COMMON_MENU_ID_KEY+\"=\"+menuId;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar tmpType = window.top.changePage(titleTxt, title, url, menuId);\r\n");
      out.write("\t\tif(tmpType){\r\n");
      out.write("\t\t\t//$menuList.find(\".active\").removeClass(\"active\");\r\n");
      out.write("\t\t\t//$obj.parents(\"li\").addClass(\"active\");\r\n");
      out.write("\t\t\t$obj.addClass(\"active\");\r\n");
      out.write("\t\t\tif($lastActiveObj){\r\n");
      out.write("\t\t\t\t$lastActiveObj.removeClass(\"active\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t$lastActiveObj = $obj;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tlastActiveMenuId = menuId;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction changeFocus(menuId){\r\n");
      out.write("\t\tvar $menu = $menuList.find(\"li\").filter(\"[MENUID=\"+menuId+\"]\").filter(\"[AMNUID!=FAVORITE]\");\r\n");
      out.write("\t\t$menu.addClass(\"active\");\r\n");
      out.write("\t\tif($lastActiveObj){\r\n");
      out.write("\t\t\t$lastActiveObj.removeClass(\"active\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t$lastActiveObj = $menu;\r\n");
      out.write("\t\tparentOpen($menu);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction parentOpen($menu){\r\n");
      out.write("\t\tvar pmenuId = $menu.attr(\"AMNUID\");\r\n");
      out.write("\t\t$menu = $menuList.find(\"li\").filter(\"[MENUID=\"+pmenuId+\"]\").filter(\"[AMNUID!=FAVORITE]\");\r\n");
      out.write("\t\tif(!$menu.hasClass(\"active\")){\r\n");
      out.write("\t\t\t$menu.find(\">a\").trigger(\"click\");\r\n");
      out.write("\t\t\tif(pmenuId != \"root\"){\r\n");
      out.write("\t\t\t\tparentOpen($menu);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tvar titleTxt = \"\";\r\n");
      out.write("\tfunction getTitle($obj){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(titleTxt){\r\n");
      out.write("\t\t\ttitleTxt = $obj.text() + \" > \" + titleTxt;\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\ttitleTxt = $obj.text();\r\n");
      out.write("\t\t}\t\t\r\n");
      out.write("\t\tvar $pObj = $obj.parent().parent().parent().siblings().find('span');\r\n");
      out.write("\t\tif($pObj.length != 0){\r\n");
      out.write("\t\t\tgetTitle($pObj);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction setLastActiveMenuId(tmpActiveMenuId){\r\n");
      out.write("\t\tif(tmpActiveMenuId){\r\n");
      out.write("\t\t\tlastActiveMenuId = tmpActiveMenuId;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction menuSearch(menuId){\r\n");
      out.write("\t\tif(!menuId){\r\n");
      out.write("\t\t\tmenuId = $menuSearch.val();\r\n");
      out.write("\t\t\tmenuId = menuId.toUpperCase();\r\n");
      out.write("\t\t\t$menuSearch.val(menuId);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar $menu = $menuList.find(\"li\").filter(\"[MENUID=\"+menuId+\"]\").filter(\"[AMNUID!=FAVORITE]\");\r\n");
      out.write("\t\tif($menu.length > 0 && lastActiveMenuId != menuId){\r\n");
      out.write("\t\t\tsetMenuClick(menuId);\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$menuSearch.val(\"\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction setMenuClick(menuId){\r\n");
      out.write("\t\tvar $menu = $menuList.find(\"li\").filter(\"[MENUID=\"+menuId+\"]\").filter(\"[AMNUID!=FAVORITE]\");\r\n");
      out.write("\t\tvar pmenuId = $menu.attr(\"AMNUID\");\r\n");
      out.write("\t\t$menu.find(\"> a\").trigger(\"click\");\r\n");
      out.write("\t\tif(pmenuId != \"root\"){\r\n");
      out.write("\t\t\tsetMenuClick(pmenuId);\r\n");
      out.write("\t\t}\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction fmenuInsert(){\r\n");
      out.write("\t\tif(lastActiveMenuId){\r\n");
      out.write("\t\t\tvar fmenu = $menuList.find(\"[AMNUID=FAVORITE]\").find(\"[MENUID=\"+lastActiveMenuId+\"]\");\r\n");
      out.write("\t\t\tif(fmenu.length == 0){\r\n");
      out.write("\t\t\t\tvar param = new DataMap();\r\n");
      out.write("\t\t\t\tparam.put(\"MENUID\",lastActiveMenuId);\r\n");
      out.write("\t\t\t\tvar json = netUtil.sendData({\r\n");
      out.write("\t\t\t\t\tmodule : \"Common\",\r\n");
      out.write("\t\t\t\t\tcommand : \"FMENU\",\r\n");
      out.write("\t\t\t\t\tsendType : \"insert\",\r\n");
      out.write("\t\t\t\t\tparam : param\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar $menu = $menuList.find(\"li\").filter(\"[MENUID=\"+lastActiveMenuId+\"]\");\r\n");
      out.write("\t\t\t\tvar $fmenu = $menuList.find(\"[MENUID=FAVORITE]\");\r\n");
      out.write("\t\t\t\tvar $tmpMenu = $($menu.clone().wrapAll(\"<div/>\").parent().html());\r\n");
      out.write("\t\t\t\t$tmpMenu.filter(\"li\").attr(\"AMNUID\", \"FAVORITE\").removeClass(\"active\").addClass(\"favmnu\");\r\n");
      out.write("\t\t\t\t$tmpMenu.append(\"<button class='delFav' onClick=\\\"fmenuDelete('\"+lastActiveMenuId+\"', this)\\\"> - </button>\");\r\n");
      out.write("\t\t\t\t//$fmenu.find(\"> a\").trigger(\"click\");\r\n");
      out.write("\t\t\t\t$fmenu.find(\"#START\").append($tmpMenu);\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\t//$menuList.find(\"[MENUID=FAVORITE]\").find(\"> a\").trigger(\"click\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction fmenuDelete(menuId, obj){\r\n");
      out.write("\t\tvar param = new DataMap();\r\n");
      out.write("\t\tparam.put(\"MENUID\",menuId);\r\n");
      out.write("\t\tvar json = netUtil.sendData({\r\n");
      out.write("\t\t\tmodule : \"Common\",\r\n");
      out.write("\t\t\tcommand : \"FMENU\",\r\n");
      out.write("\t\t\tsendType : \"delete\",\r\n");
      out.write("\t\t\tparam : param\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tjQuery(obj).parent().remove();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 로딩 열기\r\n");
      out.write("\tfunction loadingOpen() {\r\n");
      out.write("\r\n");
      out.write("\t\tvar loader = $('<div class=\"contentLoading\"></div>').appendTo('body');\r\n");
      out.write("\r\n");
      out.write("\t\tloader.stop().animate({\r\n");
      out.write("\t\t\ttop : '0px'\r\n");
      out.write("\t\t}, 30, function() {\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t// 로딩 닫기\r\n");
      out.write("\tfunction loadingClose() {\r\n");
      out.write("\r\n");
      out.write("\t\tvar loader = $('.contentLoading');\r\n");
      out.write("\r\n");
      out.write("\t\tloader.stop().animate({\r\n");
      out.write("\t\t\ttop : '100%'\r\n");
      out.write("\t\t}, 30, function() {\r\n");
      out.write("\t\t\tloader.remove();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- lnb --->\r\n");
      out.write("<div class=\"lnb\">\r\n");
      out.write("\t<div class=\"icons\">\r\n");
      out.write("\t\t<a href=\"#\"><img class=\"btn_zoom\" src=\"/common/images/btn_zoom.png\" alt=\"\" /></a>\r\n");
      out.write("\t\t<span class=\"ellipse_left\"></span>\r\n");
      out.write("\t\t<span class=\"ellipse_center\"><input type=\"text\" id=\"menuSearch\" size=\"14\" onkeypress=\"commonUtil.enterKeyCheck(event,'menuSearch()')\"/></span>\r\n");
      out.write("\t\t<span class=\"white_box\"></span>\r\n");
      out.write("\t\t<span class=\"ellipse_right\"></span>\r\n");
      out.write("\t\t<div class=\"rightArea\">\r\n");
      out.write("\t\t\t<button class=\"button type1\" type=\"button\" onclick=\"window.top.refreshPage()\"><img src=\"/common");
      out.print(theme);
      out.write("/images/ico_left3.png\" alt=\"\"></button>\t\t\r\n");
      out.write("\t\t\t<button class=\"button type1 second\" type=\"button\" onclick=\"fmenuInsert()\"><img src=\"/common");
      out.print(theme);
      out.write("/images/ico_left2.png\" alt=\"\"></button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<ul class=\"list\" id=\"menuList\" style=\"display:none;\">\r\n");
      out.write("\t\t\r\n");

	DataMap map;
	String url;
	String amnuid;
	String spanClass;
	for(int i=0;i<list.size();i++){
		map = (DataMap)list.get(i);
		url    = sFilter.getXSSFilter(map.getString("PGPATH"));
		amnuid = sFilter.getXSSFilter(map.getString("AMNUID"));
		if(url.indexOf("jsp") != -1){
			url = url.substring(1);
			url = url.substring(0, url.length()-3)+"page";
		}else{
			url = "";
		}

      out.write('\r');
      out.write('\n');

		if(amnuid.equals("FAVORITE")){
			spanClass = "fmnuTxt";			

      out.write("\t\t\t\r\n");
      out.write("\t\t<li class=\"favmnu\" AMNUID=\"");
      out.print(sFilter.getXSSFilter(map.getString("AMNUID")));
      out.write("\" MENUID=\"");
      out.print(sFilter.getXSSFilter(map.getString("MENUID")));
      out.write("\">\r\n");
 		
		}else{
			spanClass = "mnuTxt";			

      out.write("\r\n");
      out.write("\t\t<li AMNUID=\"");
      out.print(sFilter.getXSSFilter(map.getString("AMNUID")));
      out.write("\" MENUID=\"");
      out.print(sFilter.getXSSFilter(map.getString("MENUID")));
      out.write("\">\r\n");
 
		}

      out.write("\r\n");
      out.write("\r\n");

		//if(map.getString("AMNUID").equals("root")){
		if(url.equals("")){

      out.write("\r\n");
      out.write("\t\t\t<a href=\"#\">\r\n");

		}else{

      out.write("\r\n");
      out.write("\t\t\t<a href=\"#\" menuId=\"");
      out.print(sFilter.getXSSFilter(map.getString("MENUID")));
      out.write("\" onclick=\"goPage(this, '");
      out.print(url);
      out.write("')\">\r\n");

		}

      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<span class=\"");
      out.print(spanClass);
      out.write('"');
      out.write('>');
      out.print(sFilter.getXSSFilter(map.getString("LBLTXL")));
      out.write("</span>\r\n");
      out.write("\t\t\t</a>\r\n");

		if(map.getString("MENUID").equals("FAVORITE")){

      out.write("\r\n");
      out.write("\t\t\t<ul id=\"START\" style=\"display:none;\"></ul>\r\n");

		}

      out.write('\r');
      out.write('\n');

		if(map.getString("AMNUID").equals("FAVORITE")){

      out.write("\r\n");
      out.write("\t\t\t<button class=\"delFav\" onClick=\"fmenuDelete('");
      out.print(sFilter.getXSSFilter(map.getString("MENUID")));
      out.write("', this)\"> - </button>\r\n");

		}

      out.write("\r\n");
      out.write("\t\t</li>\r\n");

	}

      out.write("\r\n");
      out.write("\t</ul>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- //lnb -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar keyMap = new DataMap();\r\n");
      out.write("\tvar $menuList = $(\"#menuList\");\r\n");
      out.write("\t$menuList.hide();\r\n");
      out.write("\t$menuList.find('[AMNUID]').each(function(i,findElement){\r\n");
      out.write("\t\tvar $obj = jQuery(findElement);\r\n");
      out.write("\t\tvar AMNUID = $obj.attr(\"AMNUID\");\r\n");
      out.write("\t\tif(AMNUID != \"root\" && !keyMap.containsKey(AMNUID)){\r\n");
      out.write("\t\t\tkeyMap.put(AMNUID, AMNUID);\r\n");
      out.write("\t\t\tvar $groupList = $menuList.find(\"[AMNUID='\"+AMNUID+\"']\");\r\n");
      out.write("\t\t\t$menuList.find(\"[MENUID='\"+AMNUID+\"']\").append($groupList);\r\n");
      out.write("\t\t\t$groupList.wrapAll(\"<ul>\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t$menuList.show();\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("(function() {\r\n");
      out.write("\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\r\n");
      out.write("\t\tvar lnbTrigger = $('.lnbCloser')\r\n");
      out.write("\t\t\t, lnb = $('.lnb')\r\n");
      out.write("\t\t\t, tab = $('.tab.type1')\r\n");
      out.write("\t\t\t, contHeader = $('.contentHeader')\r\n");
      out.write("\t\t\t, content = $('.content')\r\n");
      out.write("\t\t\t, depth1Trigger = lnb.find('.list').children('li')\r\n");
      out.write("\t\t\t, depth2List = depth1Trigger.children('ul')\r\n");
      out.write("\t\t\t, depth2Trigger = depth2List.children('li')\r\n");
      out.write("\t\t\t, depth3List = depth2Trigger.children('ul')\r\n");
      out.write("\t\t\t, motionTime = 0.35\r\n");
      out.write("\t\t\t, xDist = 190;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\tdepth1Trigger.each(function() {\r\n");
      out.write("\t\t\tvar _this = $(this)\r\n");
      out.write("\t\t\t\t, thisTrigger = _this.children('a')\r\n");
      out.write("\t\t\t\t, thisDepth2List = _this.children('ul');\r\n");
      out.write("\r\n");
      out.write("\t\t\tthisTrigger.on({\r\n");
      out.write("\t\t\t\tclick : function() {\r\n");
      out.write("\t\t\t\t\tif ( thisDepth2List.is(':hidden') ) {\r\n");
      out.write("\t\t\t\t\t\t//depth1Trigger.removeClass('active');\r\n");
      out.write("\t\t\t\t\t\t_this.addClass('active');\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t//depth2List.not(thisDepth2List).stop().slideUp(200);\r\n");
      out.write("\t\t\t\t\t\tthisDepth2List.stop().slideDown(200);\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t_this.removeClass('active');\r\n");
      out.write("\t\t\t\t\t\tthisDepth2List.stop(true, true).slideUp(200);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tdepth2Trigger.each(function() {\r\n");
      out.write("\t\t\tvar _this = $(this)\r\n");
      out.write("\t\t\t\t, thisTrigger = _this.children('a')\r\n");
      out.write("\t\t\t\t, thisDepth3List = _this.children('ul');\r\n");
      out.write("\r\n");
      out.write("\t\t\tif ( thisDepth3List.length ) {\r\n");
      out.write("\t\t\t\t_this.addClass('hasDepth')\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tthisTrigger.on({\r\n");
      out.write("\t\t\t\tclick : function() {\r\n");
      out.write("\t\t\t\t\tif ( thisDepth3List.is(':hidden') ) {\r\n");
      out.write("\t\t\t\t\t\t//depth2Trigger.removeClass('active');\r\n");
      out.write("\t\t\t\t\t\t_this.addClass('active');\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t//depth3List.not(thisDepth3List).stop().slideUp(200);\r\n");
      out.write("\t\t\t\t\t\tthisDepth3List.stop().slideDown(200);\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t_this.removeClass('active');\r\n");
      out.write("\t\t\t\t\t\tthisDepth3List.stop(true, true).slideUp(200);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("})();\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
