INSERT INTO SYSLABEL
(LABELGID,LABELID,LANGCODE,LABEL,LABELTYPE)
SELECT
LABLGR, LABLKY, LANGKY, LBLTXS, 'WMS'
FROM JLBLM

INSERT INTO SYSMESSAGE
(MESSAGEGID,MESSAGEID,LANGCODE,MESSAGE,MESSAGETYPE)
SELECT
MESGGR, MESGKY, LANGKY, MESGTX, 'WMS'
FROM JMSGM

INSERT INTO MSTMENU
(COMPID,MENUID,MENULABEL,MENUNAME,MENUTYPE,MAUTHTYPE,PROGID,URI,PARAM,SORTORDER)
SELECT
'SAJO',PROGID,PROGID,SHORTX,'PAGE','PAGE',PROGID,PGPATH,'',0
FROM PROGM

INSERT INTO MSTMENU
(COMPID,MENUID,MENULABEL,MENUNAME,MENUTYPE,MAUTHTYPE,PROGID,URI,PARAM,SORTORDER)
SELECT
'SAJO',M.MENUID,M.MENUID,P.SHORTX,
M.MENUID,M.MENUID,P.PROGID,P.PGPATH,'',0
FROM (
SELECT
	MENUID
FROM MNUDT
GROUP BY MENUID
) M
LEFT OUTER JOIN PROGM P ON P.PROGID = M.MENUID

UPDATE MSTMENU SET MENUNAME = (SELECT DISTINCT JLBLM.LBLTXL FROM JLBLM WHERE JLBLM.LABLKY = MSTMENU.MENUID AND JLBLM.LANGKY = 'KO') WHERE MENUNAME IS NULL

INSERT INTO MSTMENUGL
(COMPID,MENUGID,MENUID,SORTORDER,PMENUID)
SELECT
'SAJO',MENUKY,MENUID,SORTSQ,AMNUID
FROM MNUDT

INSERT INTO MSTMENUFL
(USERID,MENUID,SORTORDER)
SELECT
USERID,MENUID,SORTSQ
FROM MNUFV
WHERE USERID ='DEV' AND MENUKY = 'DEV'