
--라벨 마이그레이션
MERGE INTO SYSLABEL SL
   USING JLBLM JL ON (JL.LABLGR = SL.LABELGID AND JL.LABLKY = SL.LABELID AND JL.LANGKY = SL.LANGCODE )
    WHEN MATCHED THEN
         UPDATE SET SL.LABEL = JL.LBLTXL
    WHEN NOT MATCHED THEN
        INSERT (SL.LABELGID, SL.LABELID, SL.LANGCODE, SL.LABEL, SL.LABELTYPE, SL.CREATEUSER, SL.CREATEDATE, SL.UPDATEUSER, SL.UPDATEDATE, SL.DELETEYN) 
        VALUES (JL.LABLGR, JL.LABLKY, JL.LANGKY, JL.LBLTXL, 'WMS', ' ', SYSDATE, ' ', SYSDATE, 'N');

INSERT INTO SYSMESSAGE
(MESSAGEGID,MESSAGEID,LANGCODE,MESSAGE,MESSAGETYPE)
SELECT
MESGGR, MESGKY, LANGKY, MESGTX, 'WMS'
FROM JMSGM

INSERT INTO MSTMENU
(COMPID,MENUID,MENULABEL,MENUNAME,MENUTYPE,MAUTHTYPE,PROGID,URI,PARAM,SORTORDER)
SELECT
'SAJO',PROGID,PROGID,SHORTX,'PAGE','PAGE',PROGID,replace(PGPATH, '.jsp', '.page') ,'',0
FROM PROGM

--중메듀 대메뉴 


INSERT INTO MSTMENU
(COMPID,MENUID,MENULABEL,MENUNAME,MENUTYPE,MAUTHTYPE,PROGID,URI,PARAM,SORTORDER)
SELECT
'SAJO',M.MENUID,M.MENUID,P.SHORTX,
M.MENUID,M.MENUID,P.PROGID,P.PGPATH,'',0
FROM (
SELECT
	MENUID
FROM MNUDT
GROUP BY MENUID
) M
LEFT OUTER JOIN PROGM P ON P.PROGID = M.MENUID

UPDATE MSTMENU SET MENUNAME = (SELECT DISTINCT JLBLM.LBLTXL FROM JLBLM WHERE JLBLM.LABLKY = MSTMENU.MENUID AND JLBLM.LANGKY = 'KO') WHERE MENUNAME IS NULL

INSERT INTO MSTMENUGL
(COMPID,MENUGID,MENUID,SORTORDER,PMENUID)
SELECT
'SAJO',MENUKY,MENUID,SORTSQ,AMNUID
FROM MNUDT

INSERT INTO MSTMENUFL
(USERID,MENUID,SORTORDER)
SELECT
USERID,MENUID,SORTSQ
FROM MNUFV
WHERE USERID ='DEV' AND MENUKY = 'DEV'


--중메뉴 
INSERT INTO MSTMENU MM
(COMPID,MENUID,MENULABEL,MENUNAME,MENUTYPE,MAUTHTYPE,PROGID,URI,PARAM,SORTORDER)
SELECT DISTINCT 'SAJO'
     , MENUID
     , MENUID
     , SL.LABEL
     , 'PAGE'
     , 'PAGE'
     , ''
     , '' 
     ,''
     ,0
 FROM MSTMENUGL MGL
      INNER JOIN SYSLABEL SL ON SL.LABELID  = MGL.MENUID 
WHERE SL.LABELGID ='MENU' AND SL.LANGCODE ='KO' 
  AND MGL.PMENUID ='MST'
  
  
 
 --대메뉴
 INSERT INTO MSTMENU MM
(COMPID,MENUID,MENULABEL,MENUNAME,MENUTYPE,MAUTHTYPE,PROGID,URI,PARAM,SORTORDER)
SELECT DISTINCT 'SAJO'
     , MGL.MENUID
     , MGL.MENUID
     , SL.LABEL
     , 'PAGE'
     , 'PAGE'
     , ''
     , '' 
     , ''
     , 0
  FROM MSTMENUGL MGL
       LEFT OUTER JOIN MSTMENU MM ON MM.MENUID = MGL.MENUID
       LEFT OUTER JOIN SYSLABEL SL ON SL.LABELGID = 'MENU' AND SL.LANGCODE = 'KO' AND MM.MENULABEL = SL.LABELID
 WHERE MENUGID = 'DEV'
   AND TRIM(SL.LABELID) IS NULL
   
   
   
--메뉴 네임 빈거 땜빵
UPDATE MSTMENU 
   SET MENUNAME = (SELECT DISTINCT LABEL FROM SYSLABEL WHERE LABELID = MSTMENU.MENUID AND LABELGID = 'MENU' AND LANGCODE = 'KO')  
 WHERE TRIM(MSTMENU.MENUNAME) IS NULL   
 
 
 
-- SYSCOMMPOP 서치헬프 헤더 
INSERT INTO SYSCOMMPOP
SELECT SHLPKY AS COMMPOPID --팝업ID
     , SHLPKY AS CPOPLABEL --팝업라벨ID
     , SHLPKY AS CPOPNAME  --팝업명 
     , STARGO AS VIEWTNAME --VIEW테이블면 STARGO
     , SHORTX AS CPOPDESC  -- 팝업설명 SHORTX
     , '' AS CPOPTYPE -- V OR 공백
     , CASE WHEN EXECTY = 'L' THEN 'V'
            ELSE ''
        END AS EXETYPE -- V OR 공백 
     , WIDTHW AS SIZEW   -- WIDTHW
     , HEIGHT AS SIZEH   -- HEIGHT
     , CREUSR AS CREATEUSER -- 생성자
     , CASE WHEN CREDAT  = '00000000' THEN SYSDATE
            ELSE TO_DATE(CREDAT)
            END AS CREATEDATE -- 생성일
     , LMOUSR AS UPDATEUSER -- 수정자
     , CASE WHEN LMODAT  = '00000000' THEN SYSDATE
            ELSE TO_DATE(LMODAT)
            END UPDATEDATE -- 수정일
     , 'N' AS DELETEYN   -- 삭제여부
  FROM SHLPH

  
  
  --서치헬프 아이템
INSERT INTO SYSCPOPITEM
SELECT SI.SHLPKY AS COMMPOPID --팝업ID 
       , SI.DBFILD AS CPOPITEMID -- 팝업item 아이디
       , SI.DBFILD AS CPOPITLABEL  -- 팝업 라벨아이디
       , (SELECT DISTINCT(LBLTXL) FROM JLBLM WHERE LABLKY ='LIFNR' AND LANGKY = 'KO' AND LABLGR ='STD') AS CPOPITNAME --팝업 라벨명
       , CASE WHEN INDUSO = 'V' AND INDULS  = 'V' THEN 'ALL'
              WHEN INDUSO = 'V' THEN 'SEARCH'
              WHEN INDULS  = 'V' THEN 'GRID'
              ELSE ' '
          END ITEMTYPE -- 검색/그리드 컬럼 존재여부
       , CASE WHEN PDATTY = '8' THEN 'CHECK'
              WHEN PDATTY = '7' THEN 'COMBO'
              ELSE 'MULTI'
          END AS SEARCHTYPE -- 조회컬럼 형태
       , CASE WHEN PDATTY = '2' THEN CASE WHEN DBDECP != 0 THEN  'N '||DBLENG||','||DBDECP  --숫자형 소숫점
                                          ELSE 'N '||DBLENG
                                      END 
              ELSE 'S '||DBLENG 
          END AS SFORMAT -- 데이터 포맷
       , '' AS SOPTION -- 조회옵션 (서치헬프 안에 서치헬프 넣을때 사용)
       , '' AS SDEFAULT  -- 초기데이터
       , CASE WHEN RQFLDS = 'V' THEN 'V'
              ELSE '' -- V이외에 값이 있는 데이터가 존재할 수 있음 
          END AS SREQUIRED -- 데이터 필수 여부
       , 100 GWIDTH    -- 컬럼크기 (구버전은 구버전기준 64고정 컬럼 없음)
       , CASE WHEN INDRVL = 'V' THEN 'T'
              ELSE ''
          END RETURNCOL --컬럼번환여부
       , CASE WHEN LENGTH(POSSOS) = 3 THEN TO_NUMBER(SUBSTR(POSSOS, 1,2)) 
              WHEN TRIM(POSSOS) IS NULL THEN 0
              ELSE TO_NUMBER(POSSOS)
          END AS SORTORDER -- 정렬순서 
       , SI.CREUSR AS CREATEUSER -- 생성자
       , CASE WHEN SI.CREDAT  = '00000000' THEN SYSDATE
              ELSE TO_DATE(SI.CREDAT)
         END AS CREATEDATE -- 생성일
       , SI.LMOUSR AS UPDATEUSER -- 수정자
       , CASE WHEN SI.LMODAT  = '00000000' THEN SYSDATE
              ELSE TO_DATE(SI.LMODAT)
          END UPDATEDATE -- 수정일
       , 'N' AS DELETEYN
    FROM SHLPI SI
         LEFT OUTER JOIN DFDIC DD ON DD.DDICKY = SI.DBFILD 
         
         
         
-- CMCDM 으로 마이그

        select COMMONID AS CMCDKY
             , COMMNAME AS SHORTX
             , ' ' AS DBFILD
             , ' ' AS USARL1
             , ' ' AS USARL2
             , ' ' AS USARL3
             , ' ' AS USARL4
             , ' ' AS USARL5
             , ' ' AS SYONLY
             , '00000000' AS CREDAT
             , '000000' AS CRETIM 
             , 'DEV' AS CREUSR
             , '00000000' AS LMODAT
             , '000000' AS LMOTIM 
             , 'DEV' AS LMOUSR
             , ' ' AS INDBZL
             , ' 'AS INDARC
             , 0 AS UPDCHK
          from SYSCOMMON         
          
          
          
        SELECT COMMONID AS CMCDKY
             , CITEMID AS CMCDVL
             , CODENAME AS CDESC1
             , ' ' AS CDESC2
             , ' ' AS USARG1
             , ' ' AS USARG2
             , ' ' AS USARG3
             , ' ' AS USARG4
             , ' ' AS USARG5
             , '00000000' AS CREDAT
             , '000000' AS CRETIM 
             , 'DEV' AS CREUSR
             , '00000000' AS LMODAT
             , '000000' AS LMOTIM 
             , 'DEV' AS LMOUSR
             , ' ' AS INDBZL
             , ' 'AS INDARC
             , 0 AS UPDCHK
          FROM SYSCOMMITEM 