/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.69
 * Generated at: 2020-04-22 09:06:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.joongwon;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.common.bean.CommonConfig;

public final class dash_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	String theme =(String)request.getSession().getAttribute(CommonConfig.SES_USER_THEME_KEY);

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script\r\n");
      out.write("  src=\"https://code.jquery.com/jquery-3.4.1.min.js\"\r\n");
      out.write("  integrity=\"sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=\"\r\n");
      out.write("  crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/common/theme/joongwon/css/dash.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\t$(\".worktab ul.worktabul li\").click(function(){\r\n");
      out.write("\t\t$(\".worktab ul.worktabul li\").removeClass('active');\r\n");
      out.write("\t\t$(this).addClass('active');\r\n");
      out.write("\t});\r\n");
      out.write("\t\t$(\".weeknumber\").hide();\r\n");
      out.write("\t\t$(\".weeknumberinner p\").click(function(){\r\n");
      out.write("\t\t\t$(\".weeknumber\").slideToggle(200);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\".weeknumber li\").click(function(){\r\n");
      out.write("\t\t\t$(this).parent().slideUp();\r\n");
      out.write("\t\t\t$(\".weeknumberinner p\").text($(this).text());\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"mainpage\">\r\n");
      out.write("\t\t<div class=\"mainleft\">\r\n");
      out.write("\t\t\t<div class=\"present\">\r\n");
      out.write("\t\t\t\t<h3>출고 및 입고 현황 </h3>\r\n");
      out.write("\t\t\t\t<table class=\"work\">\r\n");
      out.write("\t\t\t    <thead>\r\n");
      out.write("\t\t\t      <tr>\r\n");
      out.write("\t\t\t        <td>센터명</td>\r\n");
      out.write("\t\t\t        <td>입고건수</td>\r\n");
      out.write("\t\t\t        <td>입고율</td>\r\n");
      out.write("\t\t\t        <td>출고건수</td>\r\n");
      out.write("\t\t\t        <td>출고율</td>\r\n");
      out.write("\t\t\t      </tr>\r\n");
      out.write("\t\t      </thead>\r\n");
      out.write("\t\t      <tbody>\r\n");
      out.write("\t\t\t      <tr>\r\n");
      out.write("\t\t\t        <td>김포통합물류센터</td>\r\n");
      out.write("\t\t\t        <td>50,074건</td>\r\n");
      out.write("\t\t\t        <td>67%</td>\r\n");
      out.write("\t\t\t        <td>50,074</td>\r\n");
      out.write("\t\t\t        <td>67%</td>\r\n");
      out.write("\t\t\t      </tr>\r\n");
      out.write("\t\t\t      <tr>\r\n");
      out.write("\t\t\t        <td>김포통합물류센터</td>\r\n");
      out.write("\t\t\t        <td>50,074건</td>\r\n");
      out.write("\t\t\t        <td>67%</td>\r\n");
      out.write("\t\t\t        <td>50,074</td>\r\n");
      out.write("\t\t\t        <td>67%</td>\r\n");
      out.write("\t\t\t      </tr>\r\n");
      out.write("\t\t\t      <tr>\r\n");
      out.write("\t\t\t        <td>김포통합물류센터</td>\r\n");
      out.write("\t\t\t        <td>50,074건</td>\r\n");
      out.write("\t\t\t        <td>67%</td>\r\n");
      out.write("\t\t\t        <td>50,074</td>\r\n");
      out.write("\t\t\t        <td>67%</td>\r\n");
      out.write("\t\t\t      </tr>\r\n");
      out.write("\t\t\t      <tr>\r\n");
      out.write("\t\t\t        <td>김포통합물류센터</td>\r\n");
      out.write("\t\t\t        <td>50,074건</td>\r\n");
      out.write("\t\t\t        <td>67%</td>\r\n");
      out.write("\t\t\t        <td>50,074</td>\r\n");
      out.write("\t\t\t        <td>67%</td>\r\n");
      out.write("\t\t\t      </tr>\r\n");
      out.write("\t\t\t      <tr>\r\n");
      out.write("\t\t\t        <td>김포통합물류센터</td>\r\n");
      out.write("\t\t\t        <td>50,074건</td>\r\n");
      out.write("\t\t\t        <td>67%</td>\r\n");
      out.write("\t\t\t        <td>50,074</td>\r\n");
      out.write("\t\t\t        <td>67%</td>\r\n");
      out.write("\t\t\t      </tr>\r\n");
      out.write("\t\t\t      <tr>\r\n");
      out.write("\t\t\t        <td>김포통합물류센터</td>\r\n");
      out.write("\t\t\t        <td>50,074건</td>\r\n");
      out.write("\t\t\t        <td>67%</td>\r\n");
      out.write("\t\t\t        <td>50,074</td>\r\n");
      out.write("\t\t\t        <td>67%</td>\r\n");
      out.write("\t\t\t      </tr>\r\n");
      out.write("\t\t\t      <tr>\r\n");
      out.write("\t\t\t        <td>김포통합물류센터</td>\r\n");
      out.write("\t\t\t        <td>50,074건</td>\r\n");
      out.write("\t\t\t        <td>67%</td>\r\n");
      out.write("\t\t\t        <td>50,074</td>\r\n");
      out.write("\t\t\t        <td>67%</td>\r\n");
      out.write("\t\t\t      </tr>\r\n");
      out.write("\t\t\t    </tbody>\r\n");
      out.write("\t\t\t  </table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"main_contact\">\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<p class=\"contact_img\"><img src=\"/common/theme/joongwon/image/icon1.png\"></P>\r\n");
      out.write("\t\t\t\t<p class=\"contact_text\"><span>오더건수</span><br/><span>596</span></p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<p class=\"contact_img\"><img src=\"/common/theme/joongwon/image/icon2.png\"></P>\r\n");
      out.write("\t\t\t\t<p class=\"contact_text\"><span>오더건수</span><br/><span>596</span></p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<p class=\"contact_img\"><img src=\"/common/theme/joongwon/image/icon3.png\"></P>\r\n");
      out.write("\t\t\t\t<p class=\"contact_text\"><span>오더건수</span><br/><span>5556</span></p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<p class=\"contact_img\"><img src=\"/common/theme/joongwon/image/icon4.png\"></P>\r\n");
      out.write("\t\t\t\t<p class=\"contact_text\"><span>오더건수</span><br/><span>596</span></p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<p class=\"contact_img\"><img src=\"/common/theme/joongwon/image/icon5.png\"></P>\r\n");
      out.write("\t\t\t\t<p class=\"contact_text\"><span>오더건수</span><br/><span>5,916</span></p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<p class=\"contact_img\"><img src=\"/common/theme/joongwon/image/icon6.png\"></P>\r\n");
      out.write("\t\t\t\t<p class=\"contact_text\"><span>오더건수</span><br/><span>68596</span></p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"graph-inner\">\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<img src=\"/common/theme/joongwon/image/img01.png\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<img src=\"/common/theme/joongwon/image/img02.png\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<img src=\"/common/theme/joongwon/image/img03.png\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<img src=\"/common/theme/joongwon/image/img04.png\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
