/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.69
 * Generated at: 2020-10-23 07:52:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.common.bean.DataMap;
import com.common.bean.DataMap;
import java.util.*;
import com.common.bean.DataMap;
import com.common.bean.CommonConfig;

public final class search_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/common/include/searchHead.jsp", Long.valueOf(1543991574000L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	DataMap param = (DataMap)request.getAttribute("param");
	DataMap head = (DataMap)request.getAttribute("head");
	List itemList = (List)request.getAttribute("itemList");
	
	DataMap dm = (DataMap)param.get("SES_USER_INFO_ID");
	
	String area = dm.getString("AREA");
	
	TreeMap search = new TreeMap();
	TreeMap grid = new TreeMap();
	
	String returnParam = null;
	DataMap row;
	for(int i=0;i<itemList.size();i++){
		row = (DataMap)itemList.get(i);
		if(row.getString("INDRVL").equals("V")){
			returnParam = row.getString("DBFILD");
		}
		if(row.getString("INDUSO").equals("V")){
			search.put(row.getString("POSSOS"), new Integer(i));
		}
		if(row.getString("INDULS").equals("V")){
			grid.put(row.getString("POSLIS"),  new Integer(i));
		}
	}
	
	String title = head.getString("SHORTX");

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>");
      out.print(title);
      out.write("</title>\r\n");
      out.write('\r');
      out.write('\n');

	String wareky = (String)request.getSession().getAttribute(CommonConfig.SES_USER_WHAREHOUSE_KEY);
	String compky = (String)request.getSession().getAttribute(CommonConfig.SES_USER_COMPANY_KEY);
	String langky = (String)request.getSession().getAttribute(CommonConfig.SES_USER_LANGUAGE_KEY);
	String ownrky = (String)request.getSession().getAttribute(CommonConfig.SES_USER_OWNER_KEY);

	String theme =(String)request.getSession().getAttribute(CommonConfig.SES_USER_THEME_KEY);

      out.write("\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/common");
      out.print(theme);
      out.write("/css/common.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/common");
      out.print(theme);
      out.write("/css/content_body.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/common");
      out.print(theme);
      out.write("/css/content_ui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/common");
      out.print(theme);
      out.write("/css/theme.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/jquery.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/jquery-ui.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/jquery-ui.custom.js\"></script>\r\n");

	if(langky != null && (langky.equals("CN") || langky.equals("ZH"))){

      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/datepicker/jquery.ui.datepicker-zh-CN.js\"></script>\r\n");

	}else{

      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/datepicker/jquery.ui.datepicker-ko.js\"></script>\r\n");

	}

      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/jquery.plugin.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/jquery.mousewheel.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/json2.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/big.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/dataMap.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/configData.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/label.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/lang/label-");
      out.print(langky);
      out.write(".js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/lang/message-");
      out.print(langky);
      out.write(".js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/site.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/commonUtil.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common");
      out.print(theme);
      out.write("/js/theme.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/dataBind.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/input.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/netUtil.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/ui.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/worker-ajax.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/bigdata.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/dataRequest.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/grid.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/layoutSave.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/validateUtil.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/page.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("//í­ ì¸ë±ì¤ ë³ê²½\r\n");
      out.write("(function() {\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\tvar tab = $('.tab.type2')\r\n");
      out.write("\t\t\t, tabTrigger = tab.children('a');\r\n");
      out.write("\r\n");
      out.write("\t\ttabTrigger.each(function(i) {\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar zIndex = tabTrigger.length - i;\r\n");
      out.write("\r\n");
      out.write("\t\t\t$(this).css('zIndex',zIndex);\r\n");
      out.write("\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("})();\r\n");
      out.write("\r\n");
      out.write("var topGridHeight = \"160px\";\r\n");
      out.write("//ê·¸ë¦¬ë í¬ê¸° ì¡°ì \r\n");
      out.write("(function() {\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\tvar trigger = $('.fullSizer')\r\n");
      out.write("\t\t, target1 = $('.bottomSect.top')\r\n");
      out.write("\t\t, target1Height = target1.css('height')\r\n");
      out.write("\t\t, target2 = $('.bottomSect.bottom')\r\n");
      out.write("\t\t, target2OriginTop = target2.css('top');\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(target1.length > 0){\r\n");
      out.write("\t\t\ttrigger.eq(0).on({\r\n");
      out.write("\t\t\t\tclick : function() {\r\n");
      out.write("\t\t\t\t\tif ( trigger.eq(0).hasClass('folded') ) {\r\n");
      out.write("\t\t\t\t\t\ttarget1.css({ height : target1Height, bottom : 'auto' });\r\n");
      out.write("\t\t\t\t\t\ttarget2.css({ top : target2OriginTop, height : 'auto' });\r\n");
      out.write("\t\t\t\t\t\ttrigger.eq(0).removeClass('folded');\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\ttarget1.css({ height : 'auto', bottom : 10 });\r\n");
      out.write("\t\t\t\t\t\ttarget2.css({ height : 0, top : 'auto' });\r\n");
      out.write("\t\t\t\t\t\ttrigger.eq(0).addClass('folded');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\ttrigger.eq(1).on({\r\n");
      out.write("\t\t\t\tclick : function() {\r\n");
      out.write("\t\t\t\t\tif ( trigger.eq(1).hasClass('folded') ) {\r\n");
      out.write("\t\t\t\t\t\ttarget1.css({ height : target1Height, bottom : 'auto' });\r\n");
      out.write("\t\t\t\t\t\ttarget2.css({ top : target2OriginTop, height : 'auto' });\r\n");
      out.write("\t\t\t\t\t\ttrigger.eq(1).removeClass('folded');\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\ttarget1.css({ height : 0 });\r\n");
      out.write("\t\t\t\t\t\ttarget2.css({ top : 8 });\r\n");
      out.write("\t\t\t\t\t\ttrigger.eq(1).addClass('folded');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\ttarget2 = $('.bottomSect');\r\n");
      out.write("\t\t\ttarget2OriginTop = target2.css('top');\r\n");
      out.write("\t\t\ttrigger.eq(0).on({\r\n");
      out.write("\t\t\t\tclick : function() {\r\n");
      out.write("\t\t\t\t\tif ( trigger.eq(0).hasClass('folded') ) {\r\n");
      out.write("\t\t\t\t\t\ttarget2.css({ top : target2OriginTop, height : 'auto' });\r\n");
      out.write("\t\t\t\t\t\ttrigger.eq(0).removeClass('folded');\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\ttarget2.css({ top : 8 });\r\n");
      out.write("\t\t\t\t\t\ttrigger.eq(0).addClass('folded');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\t\t\r\n");
      out.write("\t});\r\n");
      out.write("})();\r\n");
      out.write("\r\n");
      out.write("// jQuery í­ ê¸°ë¥\r\n");
      out.write("(function() {\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t$('.tabs').tabs();\r\n");
      out.write("\t});\r\n");
      out.write("})();\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("// ê²ì íì\r\n");
      out.write("(function() {\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\tvar trigger = $('#showPop')\r\n");
      out.write("\t\t\t, pop = $('.searchPop')\r\n");
      out.write("\t\t\t, closer = pop.find('.closer');\r\n");
      out.write("\r\n");
      out.write("\t\ttrigger.on({\r\n");
      out.write("\t\t\tclick : function() {\r\n");
      out.write("\t\t\t\tpop.stop(true, true).fadeIn(150);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tcloser.on({\r\n");
      out.write("\t\t\tclick : function() {\r\n");
      out.write("\t\t\t\tpop.stop(true, true).fadeOut(150);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("})();\r\n");
      out.write("\r\n");
      out.write("// íì´ë¸ ì¤í¬ë¡¤\r\n");
      out.write("(function() {\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\tvar table = $('.table.type2');\r\n");
      out.write("\r\n");
      out.write("\t\ttable.each(function() {\r\n");
      out.write("\t\t\tvar _this = $(this)\r\n");
      out.write("\t\t\t\t, header = _this.find('.tableHeader')\r\n");
      out.write("\t\t\t\t, body = _this.find('.tableBody');\r\n");
      out.write("\r\n");
      out.write("\t\t\tbody.on({\r\n");
      out.write("\t\t\t\tscroll : function(e) {\r\n");
      out.write("\t\t\t\t\tvar scrollLeft = $(this).scrollLeft();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t//console.log(scrollLeft);\r\n");
      out.write("\t\t\t\t\theader.css({\r\n");
      out.write("\t\t\t\t\t\tmarginLeft : -scrollLeft\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("})();\r\n");
      out.write("\r\n");
      out.write("//ë ì¸ì§ íì\r\n");
      out.write("function rangePop() {\r\n");
      out.write("\r\n");
      out.write("\tvar\tpop = $('.layerPopup')\r\n");
      out.write("\t\t, closer = pop.find('.closer');\r\n");
      out.write("\r\n");
      out.write("\tpop.stop(true, true).fadeIn(150);\r\n");
      out.write("\tcloser.on({\r\n");
      out.write("\t\tclick : function() {\r\n");
      out.write("\t\t\tpop.stop(true, true).fadeOut(150);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function rangePopClose() {\r\n");
      out.write("\tvar\tpop = $('.layerPopup');\r\n");
      out.write("\tpop.stop(true, true).fadeOut(150);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// ê²½ê³ ì°½\r\n");
      out.write("function alertMessage() {\r\n");
      out.write("\r\n");
      out.write("\tvar alert = $('.alertMessage')\r\n");
      out.write("\t\t, closer = alert.find('.closer');\r\n");
      out.write("\r\n");
      out.write("\talert.fadeIn(150);\r\n");
      out.write("\r\n");
      out.write("\tcloser.on({\r\n");
      out.write("\t\tclick : function() {\r\n");
      out.write("\t\t\talert.fadeOut(150);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("var $contentLoading;\r\n");
      out.write("//ë¡ë© ì´ê¸°\r\n");
      out.write("function loadingOpen() {\r\n");
      out.write("\t\r\n");
      out.write("\t$contentLoading.show();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//ë¡ë© ë«ê¸°\r\n");
      out.write("function loadingClose() {\r\n");
      out.write("\t\r\n");
      out.write("\t$contentLoading.hide();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function showSearch(showType){\r\n");
      out.write("\tvar pop = $('.searchPop');\r\n");
      out.write("\r\n");
      out.write("\tif ( pop.is(':hidden') ) {\r\n");
      out.write("\t\tpop.stop(true, true).fadeIn(150);\r\n");
      out.write("\t} else {\r\n");
      out.write("\t\tpop.stop(true, true).fadeOut(150);\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function searchOpen(showType){\r\n");
      out.write("\tvar pop = $('.searchPop');\r\n");
      out.write("\tif(!showType){\r\n");
      out.write("\t\tshowType = false;\r\n");
      out.write("\t}\r\n");
      out.write("\tif (showType) {\r\n");
      out.write("\t\tpop.stop(true, true).fadeIn(150);\r\n");
      out.write("\t} else {\r\n");
      out.write("\t\tpop.stop(true, true).fadeOut(150);\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function showLayoutSave(){\r\n");
      out.write("\tvar loader = $('<div class=\"contentLayoutSave\"></div>').appendTo('body');\r\n");
      out.write("\t\r\n");
      out.write("\tloader.stop().animate({\r\n");
      out.write("\t\ttop : '0px'\r\n");
      out.write("\t}, 30, function() {\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("    $('#layoutSavePop').show();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function hideLayoutSave(){\r\n");
      out.write("\t var loader = $('.contentLayoutSave');\r\n");
      out.write("\r\n");
      out.write("\tloader.stop().animate({\r\n");
      out.write("\t\ttop : '100%'\r\n");
      out.write("\t}, 30, function() {\r\n");
      out.write("\t\tloader.remove();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$('#layoutSavePop').hide();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function setTopSize(height){\r\n");
      out.write("\t$('.bottomSect.top').css(\"height\",height+\"px\");\r\n");
      out.write("\t$('.bottomSect.bottom').css(\"top\",(height+20)+\"px\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function layoutSaveClose(){\r\n");
      out.write("\tvar loader = $('.contentLayoutSave');\r\n");
      out.write("\r\n");
      out.write("\tloader.stop().animate({\r\n");
      out.write("\t\ttop : '100%'\r\n");
      out.write("\t}, 30, function() {\r\n");
      out.write("\t\tloader.remove();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("    $('#layoutSavePop').hide();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function(){\t\t\r\n");
      out.write("\t\t$(\"body\").hide();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$contentLoading = jQuery(\"#contentLoading\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('.searchPop').stop(true, true).fadeIn(150);\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tuiList.UICheck();\r\n");
      out.write("\t\tinputList.setInput();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar openerParam = opener.dataBind.paramData(\"searchArea\");\r\n");
      out.write("\t\tif(openerParam){\r\n");
      out.write("\t\t\tdataBind.dataNameBind(openerParam, \"searchArea\");\r\n");
      out.write("\t\t\tfor(var prop in openerParam.map){\r\n");
      out.write("\t\t\t\tif(inputList.rangeMap.containsKey(prop)){\r\n");
      out.write("\t\t\t\t\tinputList.setRangeData(prop, configData.INPUT_RANGE_RANGE_FROM, openerParam.get(prop));\r\n");
      out.write("\t\t\t\t}else if(prop.indexOf(\".\")){\r\n");
      out.write("\t\t\t\t\tvar tmpProp = prop.substring(prop.indexOf(\".\")+1);\r\n");
      out.write("\t\t\t\t\tif(inputList.rangeMap.containsKey(tmpProp)){\r\n");
      out.write("\t\t\t\t\t\tinputList.setRangeData(tmpProp, configData.INPUT_RANGE_RANGE_FROM, openerParam.get(prop));\r\n");
      out.write("\t\t\t\t\t}\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfor(var prop in opener.inputList.rangeMap.map){\t\t\t\r\n");
      out.write("\t\t\tif(inputList.rangeMap.containsKey(prop)){\r\n");
      out.write("\t\t\t\tvar tmpObj = opener.inputList.rangeMap.get(prop);\r\n");
      out.write("\t\t\t\tvar inputObj = inputList.rangeMap.get(prop);\r\n");
      out.write("\t\t\t\tinputObj.singleData = tmpObj.singleData;\r\n");
      out.write("\t\t\t\tinputObj.rangeData = tmpObj.rangeData;\t\t\t\t\r\n");
      out.write("\t\t\t\tinputObj.setMultiData();\r\n");
      out.write("\t\t\t}else if(prop.indexOf(\".\")){\r\n");
      out.write("\t\t\t\tvar tmpProp = prop.substring(prop.indexOf(\".\")+1);\r\n");
      out.write("\t\t\t\tif(inputList.rangeMap.containsKey(tmpProp)){\r\n");
      out.write("\t\t\t\t\tvar tmpObj = opener.inputList.rangeMap.get(prop);\r\n");
      out.write("\t\t\t\t\tvar inputObj = inputList.rangeMap.get(tmpProp);\r\n");
      out.write("\t\t\t\t\tinputObj.singleData = tmpObj.singleData;\r\n");
      out.write("\t\t\t\t\tinputObj.rangeData = tmpObj.rangeData;\t\t\t\t\r\n");
      out.write("\t\t\t\t\tinputObj.setMultiData();\r\n");
      out.write("\t\t\t\t}\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar searchParam = window.opener.page.getSearchParam();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(searchParam){\t\t\t\r\n");
      out.write("\t\t\tdataBind.dataNameBind(searchParam, \"searchArea\");\r\n");
      out.write("\t\t\tfor(var prop in searchParam.map){\r\n");
      out.write("\t\t\t\tif(inputList.rangeMap.containsKey(prop)){\r\n");
      out.write("\t\t\t\t\tvar obj = searchParam.get(prop);\r\n");
      out.write("\t\t\t\t\tif(typeof obj == \"string\"){\r\n");
      out.write("\t\t\t\t\t\tvar inputObj = inputList.rangeMap.get(prop);\r\n");
      out.write("\t\t\t\t\t\tinputObj.searchType = \"from\";\r\n");
      out.write("\t\t\t\t\t\tinputObj.$from.val(obj);\r\n");
      out.write("\t\t\t\t\t\tinputObj.valueChange();\r\n");
      out.write("\t\t\t\t\t}else if(obj && obj.length > 0){\r\n");
      out.write("\t\t\t\t\t\tif(typeof obj[0] == \"string\"){\r\n");
      out.write("\t\t\t\t\t\t\tvar sList = new Array();\r\n");
      out.write("\t\t\t\t\t\t\tfor(var i=0;i<obj.length;i++){\r\n");
      out.write("\t\t\t\t\t\t\t\tvar tmpMap = new DataMap();\r\n");
      out.write("\t\t\t\t\t\t\t\ttmpMap.put(configData.INPUT_RANGE_LOGICAL, \"OR\");\r\n");
      out.write("\t\t\t\t\t\t\t\ttmpMap.put(configData.INPUT_RANGE_OPERATOR, \"E\");\r\n");
      out.write("\t\t\t\t\t\t\t\ttmpMap.put(configData.INPUT_RANGE_SINGLE_DATA, obj[i]);\r\n");
      out.write("\t\t\t\t\t\t\t\tsList.push(tmpMap);\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\tinputList.setRangeData(prop, configData.INPUT_RANGE_TYPE_SINGLE, sList);\r\n");
      out.write("\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\tvar sList = new Array();\r\n");
      out.write("\t\t\t\t\t\t\tvar rList = new Array();\r\n");
      out.write("\t\t\t\t\t\t\tvar tmpMap;\r\n");
      out.write("\t\t\t\t\t\t\tfor(var i=0;i<obj.length;i++){\r\n");
      out.write("\t\t\t\t\t\t\t\ttmpMap = obj[i];\r\n");
      out.write("\t\t\t\t\t\t\t\tif(tmpMap.containsKey(configData.INPUT_RANGE_SINGLE_DATA)){\r\n");
      out.write("\t\t\t\t\t\t\t\t\tif(!tmpMap.containsKey(configData.INPUT_RANGE_LOGICAL)){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttmpMap.put(configData.INPUT_RANGE_LOGICAL, \"OR\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\tif(!tmpMap.containsKey(configData.INPUT_RANGE_OPERATOR)){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttmpMap.put(configData.INPUT_RANGE_OPERATOR, \"E\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsList.push(tmpMap);\r\n");
      out.write("\t\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\t\tif(!tmpMap.containsKey(configData.INPUT_RANGE_OPERATOR)){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttmpMap.put(configData.INPUT_RANGE_OPERATOR, \"E\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\trList.push(tmpMap);\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\tif(sList.length > 0){\r\n");
      out.write("\t\t\t\t\t\t\t\tinputList.setRangeData(prop, configData.INPUT_RANGE_TYPE_SINGLE, sList);\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\tif(rList.length > 0){\r\n");
      out.write("\t\t\t\t\t\t\t\tinputList.setRangeData(prop, configData.INPUT_RANGE_TYPE_RANGE, rList);\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"body\").show();\r\n");
      out.write("\t\t$(window).resize(function(event){\r\n");
      out.write("\t\t\t//alert(window.outerHeight);\r\n");
      out.write("\t\t\tgridList.resize();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tgridList.setGrid({\r\n");
      out.write("\t\t\tid : configData.GRID_LAYOUT_SAVE_INVISIBLE_ID,\r\n");
      out.write("\t\t\teditable : false,\r\n");
      out.write("\t\t\tsortType : false,\r\n");
      out.write("\t\t\tcopyEventType : false,\r\n");
      out.write("\t\t\trowDblClickEventFn : \"layoutSave.layoutRowDblclick\"\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\tgridList.setGrid({\r\n");
      out.write("\t\t\tid : configData.GRID_LAYOUT_SAVE_VISIBLE_ID,\r\n");
      out.write("\t\t\teditable : false,\r\n");
      out.write("\t\t\tsortType : false,\r\n");
      out.write("\t\t\tcopyEventType : false,\r\n");
      out.write("\t\t\trowDblClickEventFn : \"layoutSave.layoutRowDblclick\"\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\tgridList.setGrid({\r\n");
      out.write("\t\t\tid : configData.INPUT_RANGE_SINGLEGRID_ID,\r\n");
      out.write("\t\t\teditable : false,\r\n");
      out.write("\t\t\tsortType : false,\r\n");
      out.write("\t\t\tviewFormat : true,\r\n");
      out.write("\t\t\tautoNewRowType : true,\r\n");
      out.write("\t\t\tenterKeyType : \"R\",\r\n");
      out.write("\t\t\teditedClassType : false\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\tgridList.setGrid({\r\n");
      out.write("\t\t\tid : configData.INPUT_RANGE_RANGEGRID_ID,\r\n");
      out.write("\t\t\teditable : false,\r\n");
      out.write("\t\t\tsortType : false,\r\n");
      out.write("\t\t\tviewFormat : true,\r\n");
      out.write("\t\t\tautoNewRowType : true,\r\n");
      out.write("\t\t\teditedClassType : false\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tconfigData.MENU_ID = '");
      out.print(param.getString("SHLPKY"));
      out.write("';\r\n");
      out.write("\r\n");
      out.write("\twindow.resizeTo('");
      out.print(head.getString("WIDTHW"));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(head.getString("HEIGHT"));
      out.write("');\r\n");
      out.write("\t\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\tgridList.setGrid({\r\n");
      out.write("\t    \tid : \"gridList\",\r\n");
      out.write("\t    \teditable : true,\r\n");
      out.write("\t    \t//module : \"Common\",\r\n");
      out.write("\t\t\t//command : \"SEARCH\",\r\n");
      out.write("\t\t\turl : \"/common/search/json/data.data\"\r\n");
      out.write("\t\t\t//url : \"/common/json/searchSql.data\"\r\n");
      out.write("\t    });\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");

			if(head.containsKey("EXECTY") && "V".equals(head.getString("EXECTY")) ){
		
      out.write("\r\n");
      out.write("\t\t\tsearchList();\r\n");
      out.write("\t\t");

			}
		
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tfunction searchList(){\r\n");
      out.write("\t\tif(validate.check(\"searchArea\")){\r\n");
      out.write("\t\t\tvar param = inputList.setRangeDataParam(\"searchArea\");\r\n");
      out.write("\t\t\tvar inputParam = dataBind.paramData(\"searchArea\");\r\n");
      out.write("\t\t\tparam.put(configData.INPUT_SEARCH_PARAM_KET, inputParam);\r\n");
      out.write("\t\r\n");
      out.write("\t\t\tparam.put(\"SHLPKY\",\"");
      out.print(param.getString("SHLPKY"));
      out.write("\");\r\n");
      out.write("\t\t\tgridList.gridList({\r\n");
      out.write("\t\t    \tid : \"gridList\",\r\n");
      out.write("\t\t    \tparam : param\r\n");
      out.write("\t\t    });\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//showSearch();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction searchHelpEventCloseAfter(searchCode, multyType, selectData, rowData){\r\n");
      out.write("\t\ttry{\r\n");
      out.write("\t\t\twindow.opener.searchHelpEventCloseAfter(searchCode, multyType, selectData, rowData);\r\n");
      out.write("\t\t}catch(e){\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction gridListEventRowDblclick(gridId, rowNum){\r\n");
      out.write("\t\tif(gridId != \"gridList\"){\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar rowData = gridList.getRowData(gridId, rowNum);\r\n");
      out.write("\t");

		if(param.containsKey("multyType")){
	
      out.write("\r\n");
      out.write("\t\tvar dataList = new Array();\r\n");
      out.write("\t\tdataList.push(rowData.get(\"");
      out.print(returnParam);
      out.write("\"));\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar rowList = new Array();\r\n");
      out.write("\t\trowList.push(rowData);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\twindow.opener.page.returnSearchHelp(dataList);\r\n");
      out.write("\t\tsearchHelpEventCloseAfter(configData.MENU_ID, true, dataList, rowList);\r\n");
      out.write("\t");

		}else{
	
      out.write("\r\n");
      out.write("\t\twindow.opener.page.returnSearchHelp(rowData.get(\"");
      out.print(returnParam);
      out.write("\"));\r\n");
      out.write("\t\tsearchHelpEventCloseAfter(configData.MENU_ID, false, rowData.get(\"");
      out.print(returnParam);
      out.write("\"), rowData);\r\n");
      out.write("\t");

		}
	
      out.write("\r\n");
      out.write("\t\tthis.close();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction multiSelect(){\r\n");
      out.write("\t\tvar selectData = gridList.getSelectData(\"gridList\");\r\n");
      out.write("\t\tvar rowData;\r\n");
      out.write("\t\tvar dataList = new Array();\r\n");
      out.write("\t\tfor(var i=0;i<selectData.length;i++){\r\n");
      out.write("\t\t\trowData = selectData[i];\r\n");
      out.write("\t\t\tdataList.push(rowData.get(\"");
      out.print(returnParam);
      out.write("\"));\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\twindow.opener.page.returnSearchHelp(dataList);\r\n");
      out.write("\t\tsearchHelpEventCloseAfter(configData.MENU_ID, true, dataList, selectData);\r\n");
      out.write("\t\tthis.close();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write(" \tfunction commonBtnClick(btnName){\r\n");
      out.write("\t\tif(btnName == \"Search\"){\r\n");
      out.write("\t\t\tsearchList();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"contentHeader\">\r\n");
      out.write("\t<div class=\"util\">\r\n");
      out.write("\t\t<button CB=\"Search SEARCH BTN_DISPLAY\">\r\n");
      out.write("\t\t</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"util2\">\r\n");
      out.write("\t\t<button class=\"button type2\" id=\"showPop\" type=\"button\"><img src=\"/common");
      out.print(theme);
      out.write("/images/ico_btn4.png\" alt=\"List\" /></button>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- searchPop -->\r\n");
      out.write("<div class=\"searchPop\" id=\"searchArea\">\r\n");
      out.write("\t<button type=\"button\" class=\"closer\">X</button>\r\n");
      out.write("\t<div class=\"searchInnerContainer\">\r\n");
      out.write("\t\t<p class=\"util searchBtn\">\r\n");
      out.write("\t\t\t<button CB=\"Search SEARCH BTN_DISPLAY\"></button>\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t<div class=\"searchInBox\">\r\n");
      out.write("\t\t\t<h2 class=\"tit\" CL=\"STD_SELECTOPTIONS\"></h2>\r\n");
      out.write("\t\t\t<table class=\"table type1\">\r\n");
      out.write("\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t<col width=\"100\" />\r\n");
      out.write("\t\t\t\t\t<col />\r\n");
      out.write("\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t");

					Iterator skey = search.keySet().iterator();
					String ltype = "1";
					String dfValue;
					String fType;
					while (skey.hasNext()) {
						String key = skey.next().toString();
						row = (DataMap)itemList.get(((Integer)search.get(key)).intValue());
						if(row.getString("LBTXTY").equals("M")){
							ltype = "2";
						}else if(row.getString("LBTXTY").equals("L")){
							ltype = "3";
						}else{
							ltype = "1";
						}
						
						if(!row.getString("DFVSOS").equals(" ")){
							dfValue = row.getString("DFVSOS");
						}else if(row.getString("DBFILD").equals("WAREKY")){
							dfValue = wareky;
						}else if(row.getString("DBFILD").equals("OWNRKY")){
							dfValue = ownrky;
						}else if(row.getString("DBFILD").equals("COMPKY")){
							dfValue = compky;
						}else{
							dfValue = "";
						}
						
						if(!dfValue.equals("")){
							dfValue = "value='"+dfValue+"'";
						}else{
							dfValue = "";
						}
						
						if(row.getString("OBJETY").equals("DAT")){
							fType = "UIFormat='C N'";
						}else if(row.getString("UCASOL").equals("V")){
							fType = "UIFormat='U'";
						}else{
							fType = "";
						}
				
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th CL=\"");
      out.print(row.getString("LABLGR")+"_"+row.getString("LABLKY")+","+ltype);
      out.write("\"></th>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t");

								if(row.getString("OBJETY").equals("CHB")){
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"");
      out.print(row.getString("DBFILD"));
      out.write("\" value=\"V\" ");
      out.print(row.getString("INDNED").equals("V")?"disabled='disabled'":"");
      out.write("/>\r\n");
      out.write("\t\t\t\t\t\t\t");

								}else if(row.getString("OBJETY").equals("COM")){
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"");
      out.print(row.getString("DBFILD"));
      out.write("\" CommonCombo=\"");
      out.print(row.getString("SHLPKY"));
      out.write("\" class=\"normalInput\" ");
      out.print(row.getString("RQFLDS").equals("V")?"validate='required'":"");
      out.write(">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"\"></option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t");

								}else if(row.getString("INDNED").equals("V")){
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" ");
      out.print(dfValue);
      out.write(" name=\"");
      out.print(row.getString("DBFILD"));
      out.write('"');
      out.write(' ');
      out.print(row.getString("SHLPKY").equals(" ")?"":"UIInput='S,"+row.getString("SHLPKY")+"'");
      out.write(' ');
      out.print(fType);
      out.write(" readonly='readonly' ");
      out.print(row.getString("RQFLDS").equals("V")?"validate='required'":"");
      out.write("/>\r\n");
      out.write("\t\t\t\t\t\t\t");

								}else{
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" ");
      out.print(dfValue);
      out.write(" name=\"");
      out.print(row.getString("DBFILD"));
      out.write("\" UIInput=\"R");
      out.print(row.getString("SHLPKY").equals(" ")?"":","+row.getString("SHLPKY"));
      out.write('"');
      out.write(' ');
      out.print(fType);
      out.write(' ');
      out.print(row.getString("RQFLDS").equals("V")?"validate='required'":"");
      out.write("/>\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t");

						}
				
      out.write("\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- //searchPop -->\r\n");
      out.write("\r\n");
      out.write("<!-- content -->\r\n");
      out.write("<div class=\"content\">\r\n");
      out.write("\t<div class=\"innerContainer\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- contentContainer -->\r\n");
      out.write("\t\t<div class=\"contentContainer\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"bottomSect type1\">\r\n");
      out.write("\t\t\t\t<div class=\"tabs\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"tab type2\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#tabs1-1\"><span CL='STD_SEARCH'>탭메뉴1</span></a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<div id=\"tabs1-1\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"section type1\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"table type2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"tableHeader\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<col width=\"40\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											if(param.containsKey("multyType")){
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<col width=\"40\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											}
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											skey = grid.keySet().iterator();
											while (skey.hasNext()) {
												String key = skey.next().toString();
												 
												row = (DataMap)itemList.get(((Integer)grid.get(key)).intValue());
												
												if( row.getInt("DBLENG") != row.getInt("OUTLEN") && row.getInt("OUTLEN") >= 70 ) {
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<col width=\"");
      out.print(row.getInt("OUTLEN"));
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

												}else{
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<col width=\"70\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

												}
											}
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th CL='STD_NUMBER'>번호</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											if(param.containsKey("multyType")){
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th GBtnCheck=\"true\"></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											}
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											skey = grid.keySet().iterator();
											while (skey.hasNext()) {
												String key = skey.next().toString();
												row = (DataMap)itemList.get(((Integer)grid.get(key)).intValue());
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th CL=\"");
      out.print(row.getString("LABLGR")+"_"+row.getString("LABLKY")+","+ltype);
      out.write("\"></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											}
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"tableBody\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<col width=\"40\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											if(param.containsKey("multyType")){
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<col width=\"40\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											}
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											skey = grid.keySet().iterator();
											while (skey.hasNext()) {
												String key = skey.next().toString();
												 
												row = (DataMap)itemList.get(((Integer)grid.get(key)).intValue());
												
												if( row.getInt("DBLENG") != row.getInt("OUTLEN") && row.getInt("OUTLEN") >= 70) {
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<col width=\"");
      out.print(row.getInt("OUTLEN"));
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

												}else{
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<col width=\"70\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

												}
											}
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tbody id=\"gridList\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr CGRow=\"true\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td GCol=\"rownum\">1</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");

												if(param.containsKey("multyType")){
											
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td GCol=\"rowCheck\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");

												}
											
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");

												skey = grid.keySet().iterator();
												while (skey.hasNext()) {
													String key = skey.next().toString();
													row = (DataMap)itemList.get(((Integer)grid.get(key)).intValue());
													
													if( row.getInt("DBLENG") != row.getInt("OUTLEN") ) {
													  ;
													}
											
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td GCol=\"text,");
      out.print(row.getString("DBFILD"));
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");

												}
											
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"tableUtil\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"leftArea\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										if(param.containsKey("multyType")){
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button class=\"button type8\" type=\"button\" title=\"select\" onClick=\"multiSelect()\"><img src=\"/common");
      out.print(theme);
      out.write("/images/grid_icon_01.png\" /></button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span CL=\"BTN_APPLY\" style=\"vertical-align:middle;padding-left:5px;padding-right:5px\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										}
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" GBtn=\"find\"></button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" GBtn=\"sortReset\"></button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" GBtn=\"layout\"></button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"rightArea\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"record\" GInfoArea=\"true\">17 Record</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- //contentContainer -->\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- //content -->\r\n");
      out.write("<!-- layerPop -->\r\n");
      out.write("<div class=\"layerPopup box_wrapper\">\r\n");
      out.write("\t<button type=\"button\" class=\"closer\">X</button>\r\n");
      out.write("\t<div class=\"tabs\" id=\"rangePopupTabs\">\r\n");
      out.write("\t\t<ul class=\"selection\">\r\n");
      out.write("\t\t\t<li><a href=\"#tab1\"><img src=\"/common");
      out.print(theme);
      out.write("/images/ico_t1.png\" alt=\"\" /> Single values(Inc)</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#tab2\"><img src=\"/common");
      out.print(theme);
      out.write("/images/ico_t2.png\" alt=\"\" /> Ranges(Inc)</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<div id=\"tab1\">\r\n");
      out.write("\t\t<div class=\"table type2 section\" >\r\n");
      out.write("\t\t\t<div class=\"tableHeader tbl_space tbl_small\">\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t<col width=\"40px\" />\r\n");
      out.write("\t\t\t\t\t\t<col width=\"40px\" />\r\n");
      out.write("\t\t\t\t\t\t<col width=\"250px\" />\r\n");
      out.write("\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Num</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Oper</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Single</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"tableBody tbl_small\">\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t<col width=\"40px\" />\r\n");
      out.write("\t\t\t\t\t\t<col width=\"40px\" />\r\n");
      out.write("\t\t\t\t\t\t<col width=\"250px\" />\r\n");
      out.write("\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t<tbody id=\"rangeSingleList\">\r\n");
      out.write("\t\t\t\t\t\t<tr CGRow=\"true\">\r\n");
      out.write("\t\t\t\t\t\t\t<td GCol=\"rownum\">1</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td GCol=\"select,OPER\" class=\"ico\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"E\">=</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"N\">≠</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"LT\">＜</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"GT\">＞</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"LE\">≤</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"GE\">≥</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td GCol=\"input,DATA\">DATA</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"tableUtil btn_wrap\">\r\n");
      out.write("\t\t\t\t<div class=\"leftArea\">\r\n");
      out.write("\t\t\t\t\t<button class=\"button type2\" type=\"button\" onClick=\"rangeObj.confirmRange()\"><img src=\"/common");
      out.print(theme);
      out.write("/images/ico_confirm.png\" alt=\"\" /> Confirm</button>\r\n");
      out.write("\t\t\t\t\t<button class=\"button type2\" type=\"button\" onClick=\"rangeObj.clearRange('rangeSingleList')\"><img src=\"/common");
      out.print(theme);
      out.write("/images/ico_cancel.png\" alt=\"\" /> Clear</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"rightArea\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"tab2\">\r\n");
      out.write("\t\t<div class=\"table type2 section\">\r\n");
      out.write("\t\t\t<div class=\"tableHeader tbl_space tbl_big\">\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t<col width=\"41px\" />\r\n");
      out.write("\t\t\t\t\t\t<col width=\"41px\" />\r\n");
      out.write("\t\t\t\t\t\t<col width=\"158px\"/>\r\n");
      out.write("\t\t\t\t\t\t<col width=\"174px\"/>\r\n");
      out.write("\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Num</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Oper</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>From</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>To</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"tableBody tbl_space tbl_big\">\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t<col width=\"40px\" />\r\n");
      out.write("\t\t\t\t\t\t<col width=\"40px\" />\r\n");
      out.write("\t\t\t\t\t\t<col width=\"155px\"/>\r\n");
      out.write("\t\t\t\t\t\t<col width=\"154px\"/>\r\n");
      out.write("\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t<tbody id=\"rangeRangeList\">\r\n");
      out.write("\t\t\t\t\t\t<tr CGRow=\"true\">\r\n");
      out.write("\t\t\t\t\t\t\t<td GCol=\"rownum\">1</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td GCol=\"select,OPER\" class=\"ico\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"E\">=</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"N\">≠</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td GCol=\"input,FROM\">FROM</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td GCol=\"input,TO\">TO</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"tableUtil btn_wrap\">\r\n");
      out.write("\t\t\t\t<div class=\"leftArea\">\r\n");
      out.write("\t\t\t\t\t<button class=\"button type2\" type=\"button\" onClick=\"rangeObj.confirmRange()\"><img src=\"/common");
      out.print(theme);
      out.write("/images/ico_confirm.png\" alt=\"\" /> Confirm</button>\r\n");
      out.write("\t\t\t\t\t<button class=\"button type2\" type=\"button\" onClick=\"rangeObj.clearRange('rangeRangeList')\"><img src=\"/common");
      out.print(theme);
      out.write("/images/ico_cancel.png\" alt=\"\" /> Clear</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"rightArea\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- //layerPop -->\r\n");
      out.write("\r\n");
      out.write("<!-- layout Save -->\r\n");
      out.write("<div id=\"layoutSavePop\" class=\"layoutSavePop box_wrap\">\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<div class=\"section left box_wrapper\">\r\n");
      out.write("\t\t\t<div class=\"table type3\">\r\n");
      out.write("\t\t\t\t<div class=\"tableHeader\">\r\n");
      out.write("\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"200\" />\r\n");
      out.write("\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>&nbsp;&nbsp;Invisible</th>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"tableBody tbl_wrap\">\r\n");
      out.write("\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<col />\r\n");
      out.write("\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t<tbody id=\"invisibleList\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr CGRow=\"true\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td GCol=\"text,COLTEXT\" layoutColName=\"GRID_COL_COLNAME_*\" layoutColWidth=\"GRID_COL_COLWIDTH_*\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</tbody>                 \r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"btnGroup btn_wrap\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" onClick=\"layoutSave.moveLeftAll()\" title=\"leftAll\">\r\n");
      out.write("\t\t\t\t\t<img src=\"/common");
      out.print(theme);
      out.write("/images/btn_first.png\" />\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t</br>\r\n");
      out.write("\t\t\t\t<button type=\"button\" onClick=\"layoutSave.moveLeft()\" title=\"left\">\r\n");
      out.write("\t\t\t\t\t<img src=\"/common");
      out.print(theme);
      out.write("/images/btn_prev.png\" />\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t</br>\r\n");
      out.write("\t\t\t\t<button type=\"button\" onClick=\"layoutSave.moveRight()\" title=\"right\">\r\n");
      out.write("\t\t\t\t\t<img src=\"/common");
      out.print(theme);
      out.write("/images/btn_next.png\" />\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t</br>\r\n");
      out.write("\t\t\t\t<button type=\"button\" onClick=\"layoutSave.moveRightAll()\" title=\"rightAll\">\r\n");
      out.write("\t\t\t\t\t<img src=\"/common");
      out.print(theme);
      out.write("/images/btn_last.png\" />\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"section right box_wrapper\">\r\n");
      out.write("\t\t\t<div class=\"table type3\">\r\n");
      out.write("\t\t\t\t<div class=\"tableHeader\">\r\n");
      out.write("\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"200\" />\r\n");
      out.write("\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>&nbsp;&nbsp;Visible</th>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"tableBody tbl_wrap\">\r\n");
      out.write("\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"200\" />\r\n");
      out.write("\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t<tbody id=\"visibleList\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr CGRow=\"true\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td GCol=\"text,COLTEXT\" layoutColName=\"GRID_COL_COLNAME_*\" layoutColWidth=\"GRID_COL_COLWIDTH_*\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</tbody>                 \r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t<div class=\"layoutSaveTableUtil box_wrap\">\r\n");
      out.write("\t\t\t<div class=\"leftArea\" >\r\n");
      out.write("\t\t\t\t<!-- button class=\"button type6\" type=\"button\" onClick=\"layoutSave.confirmLayout()\" title=\"Confirm\"><img src=\"/common");
      out.print(theme);
      out.write("/images/ico_confirm.png\" /> Confirm</button-->\r\n");
      out.write("\t\t\t\t<button class=\"button type6\" type=\"button\" onClick=\"layoutSaveClose()\" title=\"Cancel\"><img src=\"/common");
      out.print(theme);
      out.write("/images/ico_cancel.png\" /> Cancel</button>\r\n");
      out.write("\t\t\t\t<button class=\"button type6\" type=\"button\" onClick=\"layoutSave.saveLayout()\" title=\"Save\"><img src=\"/common");
      out.print(theme);
      out.write("/images/ico_cancel.png\" /> Save</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"rightArea\">\r\n");
      out.write("\t\t\t\t<button class=\"button type4\" type=\"button\" GBtnFind=\"true\" title=\"moveTop\" onclick=\"layoutSave.moveTop()\"><img src=\"/common");
      out.print(theme);
      out.write("/images/btn_up_02.png\" /></button>\r\n");
      out.write("\t\t\t\t<button class=\"button type4\" type=\"button\" GBtnCheck=\"true\" title=\"moveUp\" onclick=\"layoutSave.moveUp()\"><img src=\"/common");
      out.print(theme);
      out.write("/images/btn_up.png\" /></button>\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<button class=\"button type4\" type=\"button\" GBtnDelete=\"true\" title=\"moveDown\" onclick=\"layoutSave.moveDown()\"><img src=\"/common");
      out.print(theme);
      out.write("/images/btn_down.png\" /></button>\r\n");
      out.write("\t\t\t\t<button class=\"button type4\" type=\"button\" GBtnAdd=\"true\" title=\"moveBottom\" onclick=\"layoutSave.moveBottom()\"><img src=\"/common");
      out.print(theme);
      out.write("/images/btn_down_02.png\" /></button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<!-- layout Save -->\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"contentLoading\" id=\"contentLoading\"></div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
