CREATE TABLE MSTCOMP(
	COMPID		VARCHAR2(10)	PRIMARY	KEY,
	COMPLABEL	VARCHAR2(10)	,
	COMPNAME	VARCHAR2(50)	,
	SORTORDER	NUMBER			,
	AUTOSORT	NUMBER			,
	PCOMID		VARCHAR2(10)	,
	
	CREATEUSER	VARCHAR2(10)	,
	CREATEDATE	DATE			,
	UPDATEUSER	VARCHAR2(10)	,
	UPDATEDATE	DATE			,
	DELETEYN	CHAR(1)			DEFAULT 'N'
);

CREATE TABLE MSTDEPT(
	COMPID		VARCHAR2(10) ,
	DEPTID		VARCHAR2(20)	,
	DEPTLABEL	VARCHAR2(10)	,
	DEPTNAME	VARCHAR2(50)	,
	SORTORDER	NUMBER			,
	PDEPTID		VARCHAR2(10)	,
	
	CREATEUSER	VARCHAR2(10)	,
	CREATEDATE	DATE			,
	UPDATEUSER	VARCHAR2(10)	,
	UPDATEDATE	DATE			,
	DELETEYN	CHAR(1)			DEFAULT 'N',
	
	CONSTRAINTS MSTDEPT_PK PRIMARY KEY(COMPID, DEPTID)
);

CREATE TABLE MSTGRADE(
	COMPID		VARCHAR2(10) ,
	GRADEID		VARCHAR2(10)	,
	GRADELABEL	VARCHAR2(10)	,
	GRADENAME	VARCHAR2(50)	,
	SORTORDER	NUMBER			,
	
	CREATEUSER	VARCHAR2(10)	,
	CREATEDATE	DATE			,
	UPDATEUSER	VARCHAR2(10)	,
	UPDATEDATE	DATE			,
	DELETEYN	CHAR(1)			DEFAULT 'N',
	
	CONSTRAINTS MSTGRADE_PK PRIMARY KEY(COMPID, GRADEID)
);

CREATE TABLE MSTUSER(
	USERID		VARCHAR2(10)	PRIMARY	KEY,
    PASSWORD	VARCHAR2(10)	NOT	NULL,
	USERNAME	VARCHAR2(50)	,
	COMPID		VARCHAR2(10)	,
	USERTYPE	VARCHAR2(10)	,
	MENUGID		VARCHAR2(10),
	DEPTID		VARCHAR2(30),
	GRADEID		VARCHAR2(30),
	SORTORDER	NUMBER			,
	LOGINDATE	DATE			,
	LOGOUTDATE	DATE			,
	FAILCNT		NUMBER			DEFAULT 0,
	LOCKCHECK	CHAR(1)			DEFAULT ' ',
	PWDCHDATE	DATE			,
	USECHECK	CHAR(1)			DEFAULT ' ',
	USERCODE	VARCHAR2(20),
	USERG1		VARCHAR2(100),
	USERG2		VARCHAR2(100),
	USERG3		VARCHAR2(100),
	
	CREATEUSER	VARCHAR2(10)	,
	CREATEDATE	DATE			,
	UPDATEUSER	VARCHAR2(10)	,
	UPDATEDATE	DATE			,
	DELETECHECK	CHAR(1)			DEFAULT ' '
);

CREATE TABLE MSTMENUG(
	COMPID		VARCHAR2(10) 	,
	MENUGROUPID	VARCHAR2(10)	,
	MENUGLABEL	VARCHAR2(10)	,
	MENUGNAME	VARCHAR2(50)	,
	
	CREATEUSER	VARCHAR2(10)	,
	CREATEDATE	DATE			,
	UPDATEUSER	VARCHAR2(10)	,
	UPDATEDATE	DATE			,
	DELETEYN	CHAR(1)			DEFAULT 'N',
	
	CONSTRAINTS MSTMENUG_PK PRIMARY KEY(COMPID, MENUGROUPID)
);

CREATE TABLE MSTMENUGL(
	COMPID		VARCHAR2(10) 	,
	MENUGID	    VARCHAR2(10)	NOT	NULL,	
	MENUID		VARCHAR2(10)	NOT	NULL,
	SORTORDER	NUMBER			,
	PMENUID		VARCHAR2(10)	,
	
	CREATEUSER	VARCHAR2(10)	,
	CREATEDATE	DATE			,
	UPDATEUSER	VARCHAR2(10)	,
	UPDATEDATE	DATE			,
	DELETEYN	CHAR(1)			DEFAULT 'N',
	
	CONSTRAINTS MSTMENUGL_PK PRIMARY KEY(COMPID, MENUGID, MENUID)
);

CREATE TABLE MSTMENUFL(
	USERID		VARCHAR2(10)	NOT	NULL,
	MENUID		VARCHAR2(10)	NOT	NULL,
	SORTORDER	NUMBER			,
	
	CREATEUSER	VARCHAR2(10)	,
	CREATEDATE	DATE			,
	UPDATEUSER	VARCHAR2(10)	,
	UPDATEDATE	DATE			,
	DELETEYN	CHAR(1)			DEFAULT 'N',
	
	CONSTRAINTS MSTMENUFL_PK PRIMARY KEY(USERID, MENUID)
);

CREATE TABLE MSTMENU(
	COMPID		VARCHAR2(10) 	,
	MENUID		VARCHAR2(10)	,	
	MENULABEL	VARCHAR2(10)	,
	MENUNAME	VARCHAR2(50)	,
	MENUTYPE	VARCHAR2(10)	,
	MAUTHTYPE	VARCHAR2(10)	,
	PROGID		VARCHAR2(10)	,
	URI			VARCHAR2(255)	,
	PARAM		VARCHAR2(500)	,
	SORTORDER	NUMBER			,
	
	CREATEUSER	VARCHAR2(10)	,
	CREATEDATE	DATE			,
	UPDATEUSER	VARCHAR2(10)	,
	UPDATEDATE	DATE			,
	DELETEYN	CHAR(1)			DEFAULT 'N',
	
	CONSTRAINTS MSTMENU_PK PRIMARY KEY(COMPID, MENUID)
);

CREATE TABLE MSTPROG(
	COMPID		VARCHAR2(10) 	,
	PROGID		VARCHAR2(10)	,	
	PROGLABEL	VARCHAR2(10)	,
	PROGNAME	VARCHAR2(50)	,
	PROGTYPE	VARCHAR2(10)	,
	PAUTHTYPE	VARCHAR2(10)	,
	URI			VARCHAR2(255)	,
	PARAM		VARCHAR2(500) 	,
	
	CREATEUSER	VARCHAR2(10)	,
	CREATEDATE	DATE,
	UPDATEUSER	VARCHAR2(10)	,
	UPDATEDATE	DATE,
	DELETEYN	CHAR(1)			DEFAULT 'N',
	
	CONSTRAINTS MSTPROG_PK PRIMARY KEY(COMPID, PROGID)
);

CREATE TABLE SYSLABEL(
	LABELGID	VARCHAR2(10)	NOT	NULL,
	LABELID		VARCHAR2(20)	NOT	NULL,
	LANGCODE	CHAR(2)			NOT	NULL,
	LABEL		VARCHAR2(50)	NOT	NULL,
    LABELTYPE	VARCHAR2(10)	,
	
    CREATEUSER	VARCHAR2(10)	,
	CREATEDATE	DATE			,
	UPDATEUSER	VARCHAR2(10)	,
	UPDATEDATE	DATE			,
	DELETEYN	CHAR(1)			DEFAULT 'N',
	
	CONSTRAINTS SYSLABEL_PK PRIMARY KEY(LABELGID, LABELID, LANGCODE)
);

CREATE VIEW VSYSLABEL AS 
  SELECT 
    SL.LABELGID, 
    SL.LABELID, 
    KO.LABEL AS KO, 
    EN.LABEL AS EN, 
    ZH.LABEL AS ZH 
FROM 
(SELECT 
    LABELGID, 
    LABELID 
FROM SYSLABEL 
GROUP BY LABELGID,LABELID 
ORDER BY LABELGID,LABELID) SL  
LEFT OUTER JOIN SYSLABEL KO ON KO.LANGCODE = 'KO' AND SL.LABELGID = KO.LABELGID AND SL.LABELID = KO.LABELID 
LEFT OUTER JOIN SYSLABEL EN ON EN.LANGCODE = 'EN' AND SL.LABELGID = EN.LABELGID AND SL.LABELID = EN.LABELID 
LEFT OUTER JOIN SYSLABEL ZH ON ZH.LANGCODE = 'ZH' AND SL.LABELGID = ZH.LABELGID AND SL.LABELID = ZH.LABELID;

CREATE TABLE SYSMESSAGE(
	MESSAGEGID	VARCHAR2(10)		NOT	NULL,
	MESSAGEID	VARCHAR2(20)		NOT	NULL,
	LANGCODE	CHAR(2)			NOT	NULL,
	MESSAGE		VARCHAR2(500)	,
    MESSAGETYPE	VARCHAR2(10)	    ,
	
    CREATEUSER	VARCHAR2(10)	,
	CREATEDATE	DATE			,
	UPDATEUSER	VARCHAR2(10)	,
	UPDATEDATE	DATE			,
	DELETEYN	CHAR(1)			DEFAULT 'N',
	
	PRIMARY KEY(MESSAGEGID, MESSAGEID, LANGCODE)
);

CREATE VIEW VSYSMESSAGE AS 
  SELECT 
    SL.MESSAGEGID, 
    SL.MESSAGEID, 
    KO.MESSAGE AS KO, 
    EN.MESSAGE AS EN, 
    ZH.MESSAGE AS ZH 
FROM 
(SELECT 
    MESSAGEGID, 
    MESSAGEID 
FROM SYSMESSAGE 
GROUP BY MESSAGEGID,MESSAGEID 
ORDER BY MESSAGEGID,MESSAGEID) SL  
LEFT OUTER JOIN SYSMESSAGE KO ON KO.LANGCODE = 'KO' AND SL.MESSAGEGID = KO.MESSAGEGID AND SL.MESSAGEID = KO.MESSAGEID 
LEFT OUTER JOIN SYSMESSAGE EN ON EN.LANGCODE = 'EN' AND SL.MESSAGEGID = EN.MESSAGEGID AND SL.MESSAGEID = EN.MESSAGEID 
LEFT OUTER JOIN SYSMESSAGE ZH ON ZH.LANGCODE = 'ZH' AND SL.MESSAGEGID = ZH.MESSAGEGID AND SL.MESSAGEID = ZH.MESSAGEID;

CREATE TABLE SYSCOMMON(
	COMMONID	VARCHAR2(10)	PRIMARY	KEY,
	COMMLABEL 	VARCHAR2(10)	,
	COMMNAME 	VARCHAR2(50)	,
	COMMTYPE	VARCHAR2(10)	,
	
	CREATEUSER	VARCHAR2(10)	,
	CREATEDATE	DATE			,
	UPDATEUSER	VARCHAR2(10)	,
	UPDATEDATE	DATE			,
	DELETEYN	CHAR(1)			DEFAULT 'N'
);

CREATE TABLE SYSCOMMITEM(
	COMMONID	VARCHAR2(10)	NOT	NULL,
	CITEMID 	VARCHAR2(10)	NOT	NULL,
	CODELABEL	VARCHAR2(10)	,
	CODENAME	VARCHAR2(50)	,
	ITEMTYPE	VARCHAR2(10)	,
	SORTORDER	NUMBER			,
	
	CREATEUSER	VARCHAR2(10)	,
	CREATEDATE	DATE			,
	UPDATEUSER	VARCHAR2(10)	,
	UPDATEDATE	DATE			,
	DELETEYN	CHAR(1)			DEFAULT 'N',
	
	CONSTRAINTS SYSCOMMITEM_PK PRIMARY KEY(COMMONID, CITEMID)
);

CREATE TABLE SYSCOMMPOP(
	COMMPOPID	VARCHAR2(10)	PRIMARY	KEY,
	CPOPLABEL	VARCHAR2(10)	,
	CPOPNAME	VARCHAR2(50)	,
	VIEWTNAME	VARCHAR2(30)	,
	CPOPDESC	VARCHAR2(50)	,
	CPOPTYPE	VARCHAR2(10)	,
	EXETYPE		CHAR(1)			,
	SIZEW		NUMBER			DEFAULT 800,
	SIZEH		NUMBER			DEFAULT 900,
	
	CREATEUSER	VARCHAR2(10)	,
	CREATEDATE	DATE			,
	UPDATEUSER	VARCHAR2(10)	,
	UPDATEDATE	DATE			,
	DELETEYN	CHAR(1)			DEFAULT 'N'
);

CREATE TABLE SYSCPOPITEM(
	COMMPOPID	VARCHAR2(10)	NOT	NULL,
	CPOPITEMID 	VARCHAR2(10)	NOT	NULL,
	CPOPITLABEL	VARCHAR2(10)	,
	CPOPITNAME	VARCHAR2(50)	,
	ITEMTYPE	VARCHAR2(10)	NOT	NULL,
	SEARCHTYPE	VARCHAR2(10)	,
	SFORMAT		VARCHAR2(10)	,
	SOPTION		VARCHAR2(10)	,
	SDEFAULT	VARCHAR2(50)	,
	SREQUIRED	CHAR(1)			,
	GWIDTH		NUMBER			,
	RETURNCOL	CHAR(1)			,
	SORTORDER	NUMBER			,
	
	CREATEUSER	VARCHAR2(10)	,
	CREATEDATE	DATE			,
	UPDATEUSER	VARCHAR2(10)	,
	UPDATEDATE	DATE			,
	DELETEYN	CHAR(1)			DEFAULT 'N',
	
	CONSTRAINTS SYSCPOPITEM_PK PRIMARY KEY(COMMPOPID, CPOPITEMID)
);

CREATE TABLE SYSEDIREP(
	EDIID		VARCHAR2(50)	PRIMARY	KEY,
	FILENAME	VARCHAR2(50)	NOT	NULL,
	TARGET		VARCHAR2(50)	NOT	NULL,
	STARTDATE	DATE			NOT	NULL,
	SUCCESS		CHAR(1)			, -- S성공 B크기틀림 E데이터없음
	FAILDESC	VARCHAR2(500)	,
	ENDDATE		DATE			,
	DATAKEY		VARCHAR2(30)	,
	CUDSUCCESS	CHAR(1)			,
	CUDFDESC	VARCHAR2(500)	,
	
	CREATEUSER	VARCHAR2(10)	,
	CREATEDATE	DATE			,
	UPDATEUSER	VARCHAR2(10)	,
	UPDATEDATE	DATE			,
	DELETEYN	CHAR(1)			DEFAULT 'N'
);

CREATE TABLE SYSEDIERR(
	EDIID		VARCHAR2(50)	,
	EDIITEM		VARCHAR2(20)	,
	ERRTYPE		VARCHAR2(30)	,
	EDIDATA		VARCHAR2(4000)	,
	DBDATA		VARCHAR2(4000)	,
	EXCDATA		VARCHAR2(4000)	,
	
	CREATEUSER	VARCHAR2(10)	,
	CREATEDATE	DATE			,
	UPDATEUSER	VARCHAR2(10)	,
	UPDATEDATE	DATE			,
	DELETEYN	CHAR(1)			DEFAULT 'N'
);

CREATE TABLE SYSEDIINFO(
	EDIID		VARCHAR2(50)	,
	EDIITEM		VARCHAR2(20)	,
	ERRTYPE		VARCHAR2(30)	,
	EDIDATA		VARCHAR2(4000)	,
	DBDATA		VARCHAR2(4000)	,
	
	CREATEUSER	VARCHAR2(10)	,
	CREATEDATE	DATE			,
	UPDATEUSER	VARCHAR2(10)	,
	UPDATEDATE	DATE			,
	DELETEYN	CHAR(1)			DEFAULT 'N'
);

CREATE TABLE SYSUPLINFO(
	EDIID		VARCHAR2(50)	,
	EDIITEM		VARCHAR2(20)	,
	ERRTYPE		VARCHAR2(30)	,
	EDIDATA		VARCHAR2(4000)	,
	DBDATA		VARCHAR2(4000)	,
	
	CREATEUSER	VARCHAR2(10)	,
	CREATEDATE	DATE			,
	UPDATEUSER	VARCHAR2(10)	,
	UPDATEDATE	DATE			,
	DELETEYN	CHAR(1)			DEFAULT 'N'
);

CREATE TABLE SYSGRIDCOL(
	USERID		VARCHAR2(10)	NOT	NULL,
	PROGID		VARCHAR2(20)	NOT	NULL,
	GRIDID		VARCHAR2(20)	NOT	NULL,
	COLGID		VARCHAR2(20)	NOT	NULL,
	GROUPDATA	VARCHAR2(2000)	NOT	NULL,
	
	CREATEUSER	VARCHAR2(10)	,
	CREATEDATE	DATE			,
	UPDATEUSER	VARCHAR2(10)	,
	UPDATEDATE	DATE			,
	DELETEYN	CHAR(1)			DEFAULT 'N',
	
	PRIMARY KEY(USERID, PROGID, GRIDID, COLGID)
);

CREATE TABLE SYSFILEGR(
	GUUID		VARCHAR2(36) 	NOT	NULL,
	UUID		VARCHAR2(36) 	NOT	NULL,

	CREATEUSER	VARCHAR2(10)	,
	CREATEDATE	DATE			,
	UPDATEUSER	VARCHAR2(10)	,
	UPDATEDATE	DATE			,
	DELETEYN	CHAR(1)			DEFAULT 'N',
	
	PRIMARY KEY(GUUID, UUID)
);

CREATE TABLE SYSFILE(
	UUID		VARCHAR2(36) 	PRIMARY KEY,
	GUUID		VARCHAR2(36) 	, -- 그룹키
	RPATH		VARCHAR2(100)	, -- 웹상의 상대 저장경로
	PATH		VARCHAR2(100)	, -- 실제 저장경로
	FNAME		VARCHAR2(100)	, -- 저장파일명
	NAME		VARCHAR2(100)	, -- 원본파일명
	MIME		VARCHAR2(5)		, -- 저장 타입. 파일 확장자
	STYPE		VARCHAR2(5)		, -- 저장 업무 타입, image, avi, file, board-image, board-swf, board-file (공통코드 00030)
	BYTE		NUMBER			, -- 파일크기
	
	CREATEUSER	VARCHAR2(10)	,
	CREATEDATE	DATE			,
	UPDATEUSER	VARCHAR2(10)	,
	UPDATEDATE	DATE			,
	DELETEYN	CHAR(1)			DEFAULT 'N'
);
	
-- Common File Thumbnail List
CREATE TABLE SYSFILETN(
	UUID		VARCHAR2(36)	NOT	NULL, -- Common File List UUID
	PIXEL		VARCHAR2(4)		NOT	NULL, -- 썸내일 크기
	FNAME		VARCHAR2(100)	, -- 저장파일명
	
	CREATEUSER	VARCHAR2(10)	,
	CREATEDATE	DATE			,
	UPDATEUSER	VARCHAR2(10)	,
	UPDATEDATE	DATE			,
	DELETEYN	CHAR(1)			DEFAULT 'N',
	
	CONSTRAINTS SYSFILETN_PK PRIMARY KEY(UUID, PIXEL)
);

CREATE TABLE SYSLOG(
	IP			VARCHAR2(300)	,	
	URITYPE		VARCHAR2(10)	,
	URL			VARCHAR2(255)	,
	URI			VARCHAR2(255)	,	
	PARAM		VARCHAR2(255)	,
	DATA		VARCHAR2(4000)	,
	
	CREATEUSER	VARCHAR2(10)	,
	CREATEDATE	DATE			
);