/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.69
 * Generated at: 2020-11-20 02:41:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.wms;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.common.bean.CommonConfig;
import com.common.util.XSSRequestWrapper;

public final class wintabS_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');

	XSSRequestWrapper sFilter = new XSSRequestWrapper(request);
	String theme = sFilter.getXSSFilter((String)request.getSession().getAttribute(CommonConfig.SES_USER_THEME_KEY));

      out.write("\n");
      out.write("<!doctype html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<title></title>\n");
      out.write("<meta name=\"viewport\" content=\"width=1150\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/common");
      out.print(theme);
      out.write("/css/common.css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/common/theme/gsfresh/css/wintabS.css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/common/theme/gsfresh/css/theme.css\">\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/jquery.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/dataMap.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/configData.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/commonUtil.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/ui.js\"></script>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\tvar $multiList;\n");
      out.write("\tvar $pathTitle;\n");
      out.write("\t\n");
      out.write("\t$(document).ready(function(){\n");
      out.write("\t\t$multiList = jQuery(\"#multiList\");\n");
      out.write("\t\t$pathTitle = $(\"#pathTitle\");\n");
      out.write("\t\t\n");
      out.write("\t\tuiList.UICheck();\n");
      out.write("\t\t\n");
      out.write("\t\t$winTabLeft = $(\"#winTabLeft\");\n");
      out.write("\t\t$winTabRight = $(\"#winTabRight\");\n");
      out.write("\t});\n");
      out.write("\t$(window).resize(function(event){\n");
      out.write("\t\tcheckTabListSize();\n");
      out.write("\t});\n");
      out.write("\tfunction sizeToggle(self){\n");
      out.write("\t\tvar self = $(self);\n");
      out.write("\t\tvar src = self.find(\"img\").attr(\"src\");\n");
      out.write("\t\twindow.top.sizeToggle();\n");
      out.write("\t}\n");
      out.write("\tfunction activeTab($tab){\n");
      out.write("\t\t$multiList.find(\"li\").removeClass(\"active\");\n");
      out.write("\t\t$tab.addClass(\"active\");\n");
      out.write("\t\tvar menuId = $tab.attr(\"menuId\");\n");
      out.write("\t\twindow.top.changeWindow(menuId);\n");
      out.write("\t}\n");
      out.write("\tfunction changeWindow(menuId){\n");
      out.write("\t\tvar $tab = $multiList.find(\"[menuId=\"+menuId+\"]\");\n");
      out.write("\t\tif($tab.hasClass(\"active\")){\n");
      out.write("\t\t\t\n");
      out.write("\t\t}else{\n");
      out.write("\t\t\tactiveTab($tab);\n");
      out.write("\t\t}\n");
      out.write("\t\tcheckTabListSize();\n");
      out.write("\t}\n");
      out.write("\tfunction closeWindow(menuId){\n");
      out.write("\t\tvar $tabs = $multiList.find(\"[menuId=\"+menuId+\"]\");\n");
      out.write("\t\t$tabs.remove();\n");
      out.write("\t\tvar tmpActiveMenuId;\n");
      out.write("\t\tvar $tabList = $multiList.find(\"[menuId]\");\n");
      out.write("\t\tif($tabList.length >= 1){\n");
      out.write("\t\t\tvar $tmpTab = $tabList.eq($tabList.length-1);\n");
      out.write("\t\t\tif($tabs.hasClass(\"active\")){\n");
      out.write("\t\t\t\tactiveTab($tmpTab);\n");
      out.write("\t\t\t\ttmpActiveMenuId = $tmpTab.attr(\"menuId\");\n");
      out.write("\t\t\t}else{\n");
      out.write("\t\t\t\tif($tmpTab.hasClass(\"active\")){\n");
      out.write("\t\t\t\t\ttmpActiveMenuId = $tmpTab.attr(\"menuId\");\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\tif($tabList.length == 0){\n");
      out.write("\t\t\tparent.$mainFrame[0].contentWindow.infoReload();\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\twindow.top.closeWindow(menuId, tmpActiveMenuId);\n");
      out.write("\t\t\n");
      out.write("\t\tcheckTabListSize();\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tfunction closeAll(){\n");
      out.write("\t\tvar tabList = $multiList.find(\"li\");\n");
      out.write("\t\tvar menuId;\n");
      out.write("\t\tfor(var i=0;i<tabList.length;i++){\n");
      out.write("\t\t\tmenuId = tabList.eq(i).attr(\"menuId\");\n");
      out.write("\t\t\tcloseWindow(menuId);\n");
      out.write("\t\t}\n");
      out.write("\t\tparent.$mainFrame[0].contentWindow.infoReload();\n");
      out.write("\t\tcheckTabListSize();\n");
      out.write("\t}\n");
      out.write("\tfunction setPage(pathTitle, title, url, menuId){\n");
      out.write("\t\tvar width = $(\"#multiList\").width();\n");
      out.write("\t\t\n");
      out.write("\t\tvar $li = $(\"<li>\").clone();\n");
      out.write("\t\tvar $div = $(\"<div>\").clone();\n");
      out.write("\t\tvar $span = $(\"<span>\").clone();\n");
      out.write("\t\tvar $img = $(\"<img>\").clone().attr({\"src\":\"/common");
      out.print(theme);
      out.write("/images/btn_null.png\",\"alt\":\"close\"});\n");
      out.write("\t\t\n");
      out.write("\t\t$multiList.find(\"li\").removeClass(\"active\");\n");
      out.write("\t\t\n");
      out.write("\t\tvar $tmpSpan = $span.addClass(\"txt_wrap\").html(title);\n");
      out.write("\t\t$tmpSpan.click(function(event){\n");
      out.write("\t\t\tvar $obj = $(event.target);\n");
      out.write("\t\t\tvar menuId = $obj.parents(\"[menuId]\").attr(\"menuId\");\n");
      out.write("\t\t\tchangeWindow(menuId);\n");
      out.write("\t\t});\n");
      out.write("\t\t\n");
      out.write("\t\tvar $tmpObj = $li.append($div.addClass(\"tab_right\").append($tmpSpan).append($img));\n");
      out.write("\t\t$tmpObj.addClass(\"active\");\n");
      out.write("\t\t$tmpObj.attr(\"menuId\",menuId);\n");
      out.write("\t\t$tmpObj.find(\"img\").click(function(event){\n");
      out.write("\t\t\tvar $obj = $(event.target);\n");
      out.write("\t\t\tvar menuId = $obj.parents(\"[menuId]\").attr(\"menuId\");\n");
      out.write("\t\t\tcloseWindow(menuId);\n");
      out.write("\t\t});\n");
      out.write("\t\t\n");
      out.write("\t\t$multiList.append($tmpObj);\n");
      out.write("\t\t\n");
      out.write("\t\tvar $tabSpan = $tmpObj.find(\"span\");\n");
      out.write("\t\tvar w = Math.ceil($tabSpan[0].getBoundingClientRect().width);\n");
      out.write("\t\t\n");
      out.write("\t\t$tabSpan.css(\"width\",w);\n");
      out.write("\t\t$tabSpan.parent().css(\"width\",w + 7);\n");
      out.write("\t\t$tmpObj.css(\"width\",w + 32);\n");
      out.write("\t\t\n");
      out.write("\t\tcheckTabListSize();\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tvar tabBtnView = true;\n");
      out.write("\tvar $winTabLeft;\n");
      out.write("\tvar $winTabRight;\n");
      out.write("\tvar windTabWidth;\n");
      out.write("\tvar activeIndex;\n");
      out.write("\tvar $liList;\n");
      out.write("\tvar moveTabCount = 0;\n");
      out.write("\tvar maxTabCount = 0;\n");
      out.write("\tfunction checkTabListSize(){\n");
      out.write("\t\tvar tabWidth = $(\".menu-item\").width() + 1;\n");
      out.write("\t\tvar windTabWidth = 0;\n");
      out.write("\t\tvar activeWidth = 0;\n");
      out.write("\t\t\n");
      out.write("\t\tparent.$mainFrame[0].contentWindow.roopChk();\n");
      out.write("\t\tparent.parent.parent.$headFrame[0].contentWindow.topRoopChk();\n");
      out.write("\t\t\n");
      out.write("\t\t$liList = $(\"#multiList li\");\n");
      out.write("\t\tif($liList.length > 0){\n");
      out.write("\t\t\t$(\"#multiList li\").each(function(i){\n");
      out.write("\t\t\t\tif($(this).hasClass(\"active\")){\n");
      out.write("\t\t\t\t\tactiveWidth = $(this).outerWidth(true);\n");
      out.write("\t\t\t\t\tactiveIndex = i;\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\twindTabWidth += $(this).outerWidth(true);\n");
      out.write("\t\t\t});\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tvar actTabSize = activeTabSize();\n");
      out.write("\t\t\tif(actTabSize > tabWidth){\n");
      out.write("\t\t\t\tvar moveTabWidth = tabWidth - actTabSize + 60;\n");
      out.write("\t\t\t\t$multiList.css(\"left\",moveTabWidth + \"px\");\n");
      out.write("\t\t\t}else{\n");
      out.write("\t\t\t\t$multiList.css(\"left\",60);\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}else{\n");
      out.write("\t\t\t$multiList.css(\"width\",\"\");\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\tvar tabIdx = $(\"#multiList\").find(\".active\").index() + 1;\n");
      out.write("\t\tmoveTabCount = tabIdx;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tfunction setMaxTabCount(){\n");
      out.write("\t\tvar result = 0;\n");
      out.write("\t\t\n");
      out.write("\t\tvar tabWrapWidth = $(\".menu-item\").width() + 1;\n");
      out.write("\t\tvar tabWidth = $multiList.width();\n");
      out.write("\t\tvar tabCount = $multiList.children().length;\n");
      out.write("\t\tif(tabCount > 0){\n");
      out.write("\t\t\tresult = Math.ceil(tabWidth/tabWrapWidth);\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\treturn result;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tfunction setCurrentTabCount(){\n");
      out.write("\t\tvar tabIdx = $multiList.find(\".active\").index();\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tfunction activeTabSize(){\n");
      out.write("\t\tvar activeTabSize = 0;\n");
      out.write("\t\tvar isStop = false;\n");
      out.write("\t\t\n");
      out.write("\t\t$(\"#multiList\").children().each(function(){\n");
      out.write("\t\t\tif(isStop){\n");
      out.write("\t\t\t\treturn;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\tactiveTabSize += $(this).outerWidth(true);\n");
      out.write("\t\t\tif($(this).hasClass(\"active\")){\n");
      out.write("\t\t\t\tisStop = true;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t});\n");
      out.write("\t\t\n");
      out.write("\t\treturn activeTabSize;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tfunction showActiveTab(){\n");
      out.write("\t\tfor(var i=0;i<activeIndex;i++){\n");
      out.write("\t\t\t$liList.eq(i).hide();\n");
      out.write("\t\t}\n");
      out.write("\t\tfor(var i=activeIndex;i<$liList.length;i++){\n");
      out.write("\t\t\t$liList.eq(i).show();\n");
      out.write("\t\t}\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tfunction tabLeft(){\n");
      out.write("\t\tvar $tabList = $(\"#multiList li\");\n");
      out.write("\t\t\n");
      out.write("\t\tvar moveTabSize = commonUtil.parseInt(commonUtil.replaceAll($(\"#multiList\").css(\"left\"),\"px\",\"\"));\n");
      out.write("\t\tvar activeTabSize  = $tabList.eq(moveTabCount - 1).outerWidth(true);\n");
      out.write("\t\t\n");
      out.write("\t\tmoveTabSize = moveTabSize + activeTabSize;\n");
      out.write("\t\t\n");
      out.write("\t\tif(moveTabSize >= 60){\n");
      out.write("\t\t\tmoveTabSize = 60;\n");
      out.write("\t\t\tmoveTabCount = 1;\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\t$(\"#multiList\").css(\"left\",moveTabSize + \"px\");\n");
      out.write("\t\t\n");
      out.write("\t\tif(moveTabCount <= 1){\n");
      out.write("\t\t\tmoveTabCount = 1;\n");
      out.write("\t\t\treturn;\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\tmoveTabCount--;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tfunction tabRight(){\n");
      out.write("\t\tvar totalMenuCount = $liList.length;\n");
      out.write("\t\t\n");
      out.write("\t\tvar wrapTabSize = $(\".menu-item\").width() + 1;\n");
      out.write("\t\tvar currentTabSize = $(\"#multiList\").width();\n");
      out.write("\t\t\n");
      out.write("\t\tif(wrapTabSize >= currentTabSize){\n");
      out.write("\t\t\treturn;\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\tvar moveTabSize = commonUtil.parseInt(commonUtil.replaceAll($(\"#multiList\").css(\"left\"),\"px\",\"\"));\n");
      out.write("\t\tvar activeTabSize  = $(\"#multiList\").children().eq(totalMenuCount - (totalMenuCount - moveTabCount) - 1).outerWidth(true);\n");
      out.write("\t\t\n");
      out.write("\t\tmoveTabSize = moveTabSize - activeTabSize;\n");
      out.write("\t\t\n");
      out.write("\t\tif(wrapTabSize > ((currentTabSize + moveTabSize) -60)){\n");
      out.write("\t\t\tmoveTabSize = (wrapTabSize - currentTabSize) + 60;\n");
      out.write("\t\t\t$(\"#multiList\").css(\"left\",moveTabSize + \"px\");\n");
      out.write("\t\t\t\n");
      out.write("\t\t\treturn;\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\tif(totalMenuCount <= moveTabCount){\n");
      out.write("\t\t\tmoveTabCount = totalMenuCount;\n");
      out.write("\t\t\tmoveTabSize = (($(\".menu-item\").width() + 1) - $(\"#multiList\").width()) + 60;\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t$(\"#multiList\").css(\"left\",moveTabSize + \"px\");\n");
      out.write("\t\t\t\n");
      out.write("\t\t\treturn;\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\t$(\"#multiList\").css(\"left\",moveTabSize + \"px\");\n");
      out.write("\t\t\n");
      out.write("\t\tmoveTabCount++;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tfunction isMaxTab(){\n");
      out.write("\t\tvar tabWidth = $(\".menu-item\").width() + 1;\n");
      out.write("\t\tvar activeTabSize = 0;\n");
      out.write("\t\tfor(var i = 0; i < moveTabCount; i++){\n");
      out.write("\t\t\tactiveTabSize += $(\"#multiList\").children().eq(i).find(\".tab_right\").width() + 22;\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\tvar winTabSize = $(\"#multiList\").width();\n");
      out.write("\t\tvar moveTabSize = ((activeTabSize * -1) + 60);\n");
      out.write("\t\t\n");
      out.write("\t\tif(tabWidth >= (winTabSize + moveTabSize)){\n");
      out.write("\t\t\treturn true;\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\treturn false;\n");
      out.write("\t}\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("<body class=\"content_header\">\n");
      out.write("<div class=\"tab type1\" id=\"windowTabs\" style=\"overflow:hidden; height:25px;\">\n");
      out.write("\t<button class=\"menu lnbCloser\" onclick=\"sizeToggle(this)\"></button>\n");
      out.write("\t<div class=\"menu-info\" id=\"pathTitle\">\n");
      out.write("\t\t<div class=\"all_close\" id=\"allClose\">\n");
      out.write("\t\t\t<img src=\"/common/theme/gsfresh/images/login_img/btn_closeAll-black.png\" alt=\"close\" onClick=\"closeAll()\" />\n");
      out.write("\t\t</div>\n");
      out.write("\t\t <div class=\"tab_list\" id=\"tabList\">\n");
      out.write("\t\t\t<img src=\"/common/theme/gsfresh/images/login_img/list_left.png\" alt=\"left\"  id=\"winTabLeft\" onClick=\"tabLeft()\" />\n");
      out.write("\t\t\t<img src=\"/common/theme/gsfresh/images/login_img/list_right.png\" alt=\"right\" id=\"winTabRight\" onClick=\"tabRight()\" />\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<div class=\"menu-item\">\n");
      out.write("\t\t<ul id=\"multiList\"></ul>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
